In [1]:
import pandas as pd
import numpy as np
from os import path, listdir
from collections import defaultdict
import alphastats
from alphastats.loader import DIANNLoader
from alphastats.dataset import dataset
import directlfq.lfq_manager as lfq_manager
import scipy as sc
import matplotlib.pyplot as plt
from pyteomics import fasta

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

/home/lerost/.pyenv/versions/3.10.11_alphastats/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedCheckFailedWarning: Failed to check for latest version of package.
Set the environment variable OUTDATED_RAISE_EXCEPTION=1 for a full traceback.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
help(dataset.DataSet.plot_volcano)

Help on function plot_volcano in module alphastats.dataset.dataset:

plot_volcano(self, group1: Union[str, list], group2: Union[str, list], column: str = None, method: str = 'ttest', labels: bool = False, min_fc: float = 1.0, alpha: float = 0.05, draw_line: bool = True, perm: int = 100, fdr: float = 0.05, color_list: list = None)
    Plot Volcano Plot

    Args:
        column (str): column name in the metadata file with the two groups to compare
        group1 (str/list): name of group to compare needs to be present in column or list of sample names to compare
        group2 (str/list): name of group to compare needs to be present in column  or list of sample names to compare
        method (str): "anova", "wald", "ttest", "SAM" Defaul ttest.
        labels (bool): Add text labels to significant Proteins, Default False.
        alpha(float,optional): p-value cut off.
        min_fc (float): Minimum fold change.
        draw_line(boolean): whether to draw cut off lines.
        perm(float,optional): number of permutations when using SAM as method. Defaults to 100.
        fdr(float,optional): FDR cut off when using SAM as method. Defaults to 0.05.
        color_list (list): list with ProteinIDs that should be highlighted.
        #compare_preprocessing_modes(bool): Will iterate through normalization and imputation modes and return a list of VolcanoPlots in different settings, Default False.


    Returns:
        plotly.graph_objects._figure.Figure: Volcano Plot

In [23]:
!pip list | grep "pyteomics"

pyteomics                 4.7.5

# Fasta

In [5]:
# fasta_path = './fasta/human_ecoli_yeast_13072026.fasta'

# fasta_path = './fasta/sprot_ecoli_ups.fasta'

# i = 0
# test_dct = {'Human':set(), 'Ecoli':set(), 'Yeast':set() , 'Other':set()}
# with open(fasta_path, mode='r') as f:
#     for descr, seq in fasta.read(f) :
#         i += 1
#         if descr.startswith('sp|') :
#             prot_id = descr.split('|')[1]
#         else :
#             prot_id = descr
#         if 'HUMAN' in descr :
#             test_dct['Human'].add(prot_id)
#         elif 'ECOLI' in descr :
#             test_dct['Ecoli'].add(prot_id)
#         elif 'YEAST' in descr :
#             test_dct['Yeast'].add(prot_id)
#         else :
#             test_dct['Other'].add(prot_id)

# for key in test_dct.keys() :
#     print(key, 
#         len(test_dct[key])
#     )
# print('intersection',
#     len(test_dct['Human'] & test_dct['Ecoli']), 
#     len(test_dct['Yeast'] & test_dct['Ecoli']),
#     len(test_dct['Human'] & test_dct['Yeast'])
# )
        # if i >= 40 and i <= 50 :
        #     print(descr)
        # if i >= 300 :
        #     break

In [6]:
fasta_path = './fasta/sprot_ecoli_ups.fasta'

i = 0
ups_ecoli_organism_dict = defaultdict(lambda :'Other')
with open(fasta_path, mode='r') as f:
    for descr, seq in fasta.read(f) :
        if descr.startswith('sp|') :
            prot_id = descr.split('|')[1]
        else :
            prot_id = descr
        if 'HUMAN' in descr :
            ups_ecoli_organism_dict[prot_id] = 'Human'
            ups_ecoli_organism_dict[prot_id.split(' ')[0]] = 'Human'
        elif 'ECOLI' in descr :
            ups_ecoli_organism_dict[prot_id] = 'Ecoli'
        else :
            ups_ecoli_organism_dict[prot_id] = 'Other'
            # ups_ecoli_organism_dict['Other'].add(prot_id)

In [7]:
fasta_path = './fasta/sprot_ecoli_ups_15072026_shuffled.fasta'

i = 0
double_ups_ecoli_organism_dict = defaultdict(lambda :'Other')
with open(fasta_path, mode='r') as f:
    for descr, seq in fasta.read(f) :
        if len(descr.split('|')) > 2 :
            prot_id = descr.split('|')[1]
        else :
            prot_id = descr
        if 'HUMAN' in descr :
            double_ups_ecoli_organism_dict[prot_id] = 'Human'
        elif 'ECOLI' in descr :
            double_ups_ecoli_organism_dict[prot_id] = 'Ecoli'
        else :
            double_ups_ecoli_organism_dict[prot_id] = 'Other'
            # double_ups_ecoli_organism_dict['Other'].add(prot_id)

In [8]:
fasta_path = './fasta/human_ecoli_yeast_13072026.fasta'

h = 0
e = 0
y = 0
o = 0
i = 0
lfqbench_organism_dict = defaultdict(lambda :'Other')
with open(fasta_path, mode='r') as f:
    for descr, seq in fasta.read(f) :
        i += 1
        if len(descr.split('|')) > 2 :
            prot_id = descr.split('|')[1]
        else :
            prot_id = descr
        if 'HUMAN' in descr :
            lfqbench_organism_dict[prot_id] = 'Human'
            lfqbench_organism_dict[prot_id.split(' ')[0]] = 'Human'
            h += 1
        elif 'ECOLI' in descr :
            lfqbench_organism_dict[prot_id] = 'Ecoli'
            e += 1
        elif 'YEAST' in descr :
            lfqbench_organism_dict[prot_id] = 'Yeast'
            y += 1
        else :
            lfqbench_organism_dict[prot_id] = 'Other'
            # lfqbench_organism_dict['Other'].add(prot_id)
            o += 1
        # if 'A0ACI8SQ87' in descr :
        #     print(descr, seq)
print(h, e, y, o)
        # if i >= 40 and i <= 50 :
        #     print(descr, prot_id)
        # if i >= 300 :
        #     break

20652 4403 6066 0

In [9]:
fasta_path = './fasta/human_ecoli_yeast_13072026_shuffled.fasta'

i = 0
double_lfqbench_organism_dict = defaultdict(lambda :'Other')
with open(fasta_path, mode='r') as f:
    for descr, seq in fasta.read(f) :
        if descr.startswith('sp|') :
            prot_id = descr.split('|')[1]
        else :
            prot_id = descr
        if 'HUMAN' in descr :
            double_lfqbench_organism_dict[prot_id] = 'Human'
        elif 'ECOLI' in descr :
            double_lfqbench_organism_dict[prot_id] = 'Ecoli'
        elif 'YEAST' in descr :
            double_lfqbench_organism_dict[prot_id] = 'Yeast'
        else :
            double_lfqbench_organism_dict[prot_id] = 'Other'
            # double_lfqbench_organism_dict['Other'].add(prot_id)

In [10]:
i = 0
h = 0
e = 0
y = 0
for k, v in lfqbench_organism_dict.items() :
    if v == 'Human' :
        h += 1
    elif v == 'Ecoli' :
        e += 1
    elif v == 'Yeast' :
        y += 1
    i ++ 1
print(h, e, y)

20652 4403 6066

In [11]:
# example_input_file_diann = "/path/to/example_input_file_diann.tsv"

# lfq_manager.run_lfq(example_input_file_diann)

# Functions

In [12]:
def alpha_quant(infile, colstarter='', colsplitter='', condstarter='', imputation='mean', organism_dict={}, min_fc=0.5, search_engine='', save_path='') :
    # infile :str - path to report.pg_matrix.tsv from diann
    # colstarter :str - starter of the individual file name
    # colsplitter :str - pattern to split the colname in pair with starter to get condition
    # imputation :str - imputation method
    # min_fc :float - fc threshold
    # search_engine :str - search engine label to store
    
    df = pd.read_csv(infile, sep='\t')
    alphastats_meta_path = infile.replace('pg_matrix.tsv', 'alphastats.meta.tsv')
    all_columns = list(df.columns)
    try :
        samples = sorted([path.basename(col) for col in all_columns if col.startswith(colstarter)], 
                         # path.basename(col)+'_Intensity'
                         key=lambda x: float(x.split(path.basename(colstarter))[-1].split('fmol')[0].replace('_', '.')) + 0.0001*int(x.split('inj')[-1][0]),
                         reverse=False)
        temp_conds = sorted([condstarter+col.split(colstarter)[-1].split(colsplitter)[0] for col in all_columns if col.startswith(colstarter)],
                            key=lambda x: float(x.split('fmol')[0].replace('_', '.')),
                            reverse=False)
        conds = sorted(list(set(temp_conds)), 
                       key=lambda x: float(x.split('fmol')[0].replace('_', '.')),
                       reverse=False)
    except :
        samples = sorted([path.basename(col) for col in all_columns if col.startswith(colstarter)], 
                         reverse=False)
        temp_conds = sorted([condstarter+col.split(colstarter)[-1].split(colsplitter)[0] for col in all_columns if col.startswith(colstarter)],
                            reverse=False)
        conds = sorted(list(set(temp_conds)))
    a = pd.DataFrame([samples, temp_conds], index=['sample', 'condition']).T
    a.to_csv(alphastats_meta_path, sep='\t', index=False)
    
    dia_data = DIANNLoader(file=infile)
    print("Data columns:", dia_data.rawinput.columns.tolist())
    # print("Sample names from loader:", dia_data.sample_names)
    print("Metadata sample names:", a['sample'].tolist())
    my_dataset = dataset.DataSet(
    loader = dia_data,
    metadata_path_or_df=alphastats_meta_path,
    sample_column="sample"
    )
    my_dataset.preprocess(
        remove_contaminations=True,
        subset=True,
        # normalization='quantile',
        imputation=imputation,)
    
    plot = my_dataset.plot_volcano(column = "condition", 
                                group1 = conds[0], 
                                group2 = conds[1], 
                                min_fc = min_fc)
    plot_df = plot.plotting_data
    plot_df.sort_values('pval', inplace=True)
    ll = len(plot_df)
    plot_df['FC_pass'] = np.abs(plot_df['log2fc']) >= min_fc
    bonf = 0.05/ll
    plot_df['Bonf_pass'] = plot_df['pval'] <= bonf
    plot_df['BH_thr'] = [0.05*i/ll for i in range(1, ll+1, 1)]
    plot_df['BH_pass'] = (plot_df['pval'] <= plot_df['BH_thr']).cummin()
    if plot_df['BH_pass'].sum() > 0 :
        border_fdr = plot_df[plot_df['BH_pass']]['pval'].max()
    else :
        border_fdr = 0.05
    # print(plot_df.columns)
    # print(plot_df.head(50))
    
    # break
    plot_df['Organism'] = plot_df['index_'].map(lambda x : list(set([organism_dict[el] for el in x.split(';')]))[0] if len(set([organism_dict[el] for el in x.split(';')]))==1 else 'Contamination').copy()
    plot_df = plot_df.rename(columns={ 'index_':'Protein.Group', })
    plot_df['Human'] = plot_df['Organism'] == 'Human'
    plot_df['Ecoli'] = plot_df['Organism'] == 'Ecoli'
    plot_df['Yeast'] = plot_df['Organism'] == 'Yeast'
    plot_df['FDR_pass'] = plot_df['BH_pass']
    plot_df['Search Engine'] = [search_engine for _ in range(len(plot_df))]
    plot_df['Quantitation'] = ['AlphaPeptStats' for _ in range(len(plot_df))]
    plot_df['Imputation'] = [str(imputation) for _ in range(len(plot_df))]
    plot_df['FC_thr'] = [min_fc for _ in range(len(plot_df))]
    
    if save_path :
        plot_df.to_csv(save_path, index=False, sep='\t')
    else :
        print('not saving results', save_path)
    de = len(plot_df[(plot_df['FDR_pass'] & plot_df['FC_pass'])])
    h_de = len(plot_df[(plot_df['Human'] & plot_df['FDR_pass'] & plot_df['FC_pass'])])
    e_de = len(plot_df[(plot_df['Ecoli'] & plot_df['FDR_pass'] & plot_df['FC_pass'])])
    y_de = len(plot_df[(plot_df['Yeast'] & plot_df['FDR_pass'] & plot_df['FC_pass'])])
    return de, h_de, e_de, y_de, plot_df

In [13]:
def manual_quant(infile, 
                 colstarter='', 
                 colsplitter='', 
                 condstarter='', 
                 imputation='mean', 
                 organism_dict={}, 
                 prot_col='', 
                 min_fc=0.5, 
                 max_nan=3, 
                 search_engine='', 
                 quant='', 
                 save_path='') :
    # infile :str - path to report.pg_matrix.tsv from diann
    # colstarter :str - starter of the individual file name
    # colsplitter :str - pattern to split the colname in pair with starter to get condition
    # max_nan :int - maximum number of nan intensities for 
    # imputation :str - imputation method
    # min_fc :float - fc threshold
    # search_engine :str - search engine label to store
    # quant :str - quantitation label to store
    
    lfq_df = pd.read_csv(infile, sep='\t')
    all_cols = list(lfq_df.columns)
    print(all_cols)
    cols = [col for col in all_cols if col.startswith(colstarter) ]
    conds = sorted(list(set([condstarter+col.split(colstarter)[-1].split(colsplitter)[0] for col in cols ])))
    cols_A = [col for col in cols if condstarter+col.split(colstarter)[-1].split(colsplitter)[0] == conds[0] ]
    cols_B = [col for col in cols if condstarter+col.split(colstarter)[-1].split(colsplitter)[0] == conds[1] ]
    # print(cols_A, cols_B, sep='\n')
    lfq_df = lfq_df.replace(to_replace={0:np.nan},)
    lfq_df['isna'] = lfq_df[cols].isna().sum(axis=1)
    lfq_df = lfq_df[lfq_df['isna'] <= max_nan].copy()
    for col in cols :
        m = lfq_df[col].min()
        lfq_df[col] = lfq_df[col].replace(to_replace={np.nan:m}).apply(pd.to_numeric, errors='coerce')
    # print(lfq_df[cols].isna().sum())
    lfq_df['pval'] = lfq_df.apply(lambda row: sc.stats.ttest_ind(row[cols_A].to_list(), row[cols_B].to_list(), equal_var=False).pvalue, axis=1)
    lfq_df['log2_FC'] = np.log2(lfq_df[cols_A].mean(skipna=True, axis=1) / lfq_df[cols_B].mean(skipna=True, axis=1))
    ll = len(lfq_df)
    bonf_thr = 0.05/ll
    lfq_df['Bonf_pass'] = lfq_df['pval'] <= bonf_thr
    lfq_df.sort_values('pval', inplace=True)
    lfq_df['BH_thr'] = [0.05*i/ll for i in range(1, ll+1, 1)]
    lfq_df['BH_pass'] = (lfq_df['pval'] <= lfq_df['BH_thr']).cummin()
    lfq_df['FC_pass'] = abs(lfq_df['log2_FC']) > min_fc
    if lfq_df['BH_pass'].sum() > 0 :
        border_fdr = lfq_df[lfq_df['BH_pass']]['pval'].max()
    else :
        border_fdr = 0.05

    if prot_col :
        lfq_df['Organism'] = lfq_df[prot_col].map(lambda x : list(set([organism_dict[el] for el in x.split(';')]))[0] if len(set([organism_dict[el] for el in x.split(';')]))==1 else 'Contamination').copy()
    else :
        lfq_df['Organism'] = lfq_df['Protein.Group'].map(lambda x : list(set([organism_dict[el] for el in x.split(';')]))[0] if len(set([organism_dict[el] for el in x.split(';')]))==1 else 'Contamination').copy()
    lfq_df['Human'] = lfq_df['Organism'] == 'Human'
    lfq_df['Ecoli'] = lfq_df['Organism'] == 'Ecoli'
    lfq_df['Yeast'] = lfq_df['Organism'] == 'Yeast'
    lfq_df['FDR_pass'] = lfq_df['BH_pass']
    lfq_df['Search Engine'] = [search_engine for _ in range(len(lfq_df))]
    lfq_df['Quantitation'] = [quant for _ in range(len(lfq_df))]
    lfq_df['Imputation'] = [imputation for _ in range(len(lfq_df))]
    lfq_df['FC_thr'] = [min_fc for _ in range(len(lfq_df))]

    if save_path :
        lfq_df.to_csv(save_path, index=False, sep='\t')
    else :
        print('not saving results', save_path)
    de = len(lfq_df[(lfq_df['FDR_pass'] & lfq_df['FC_pass'])])
    h_de = len(lfq_df[(lfq_df['Human'] & lfq_df['FDR_pass'] & lfq_df['FC_pass'])])
    e_de = len(lfq_df[(lfq_df['Ecoli'] & lfq_df['FDR_pass'] & lfq_df['FC_pass'])])
    y_de = len(lfq_df[(lfq_df['Yeast'] & lfq_df['FDR_pass'] & lfq_df['FC_pass'])])
    return de, h_de, e_de, y_de, lfq_df

In [40]:
lfq_df = pd.read_csv('./search_results/diann231_ups_ecoli/5fmol_vs_0_25fmol/quant_directlfq_min.tsv', sep='\t')
lfq_df.head()

,protein,RD139_Wide_UPS1_0_25fmol_inj1,RD139_Wide_UPS1_0_25fmol_inj2,RD139_Wide_UPS1_0_25fmol_inj3,RD139_Wide_UPS1_5fmol_inj1,RD139_Wide_UPS1_5fmol_inj2,RD139_Wide_UPS1_5fmol_inj3,isna,pval,log2_FC,Bonf_pass,BH_thr,BH_pass,FC_pass,Organism,Human,Ecoli,Yeast,FDR_pass,Search Engine,Quantitation,Imputation,FC_thr
0,P67662,141297.235101,133796.22389,115453.070052,9.217357e+05,9.697915e+05,9.457159e+05,3,0.000011,-2.860923,True,0.000024,True,True,Ecoli,False,True,False,True,diann231,directlfq,min,1.660964
1,O00762ups|UBE2C_HUMAN_UPS,141297.235101,133796.22389,115453.070052,1.363752e+07,1.387897e+07,1.397899e+07,3,0.000050,-6.731316,False,0.000049,False,True,Human,True,False,False,False,diann231,directlfq,min,1.660964
2,P02787ups|TRFE_HUMAN_UPS,141297.235101,133796.22389,115453.070052,7.026252e+07,7.000102e+07,6.847235e+07,3,0.000064,-9.061969,False,0.000073,True,True,Human,True,False,False,True,diann231,directlfq,min,1.660964
3,P02788ups|TRFL_HUMAN_UPS,141297.235101,133796.22389,115453.070052,9.663253e+07,9.575312e+07,9.845434e+07,3,0.000067,-9.540516,False,0.000098,True,True,Human,True,False,False,True,diann231,directlfq,min,1.660964
4,P01008ups|ANT3_HUMAN_UPS,141297.235101,133796.22389,115453.070052,4.676472e+07,4.669985e+07,4.818103e+07,3,0.000105,-8.502576,False,0.000122,True,True,Human,True,False,False,True,diann231,directlfq,min,1.660964

In [41]:
lfq_df['BH_pass'] = (lfq_df['pval'] <= lfq_df['BH_thr']).cummin()
lfq_df.head()

,protein,RD139_Wide_UPS1_0_25fmol_inj1,RD139_Wide_UPS1_0_25fmol_inj2,RD139_Wide_UPS1_0_25fmol_inj3,RD139_Wide_UPS1_5fmol_inj1,RD139_Wide_UPS1_5fmol_inj2,RD139_Wide_UPS1_5fmol_inj3,isna,pval,log2_FC,Bonf_pass,BH_thr,BH_pass,FC_pass,Organism,Human,Ecoli,Yeast,FDR_pass,Search Engine,Quantitation,Imputation,FC_thr
0,P67662,141297.235101,133796.22389,115453.070052,9.217357e+05,9.697915e+05,9.457159e+05,3,0.000011,-2.860923,True,0.000024,True,True,Ecoli,False,True,False,True,diann231,directlfq,min,1.660964
1,O00762ups|UBE2C_HUMAN_UPS,141297.235101,133796.22389,115453.070052,1.363752e+07,1.387897e+07,1.397899e+07,3,0.000050,-6.731316,False,0.000049,False,True,Human,True,False,False,False,diann231,directlfq,min,1.660964
2,P02787ups|TRFE_HUMAN_UPS,141297.235101,133796.22389,115453.070052,7.026252e+07,7.000102e+07,6.847235e+07,3,0.000064,-9.061969,False,0.000073,False,True,Human,True,False,False,True,diann231,directlfq,min,1.660964
3,P02788ups|TRFL_HUMAN_UPS,141297.235101,133796.22389,115453.070052,9.663253e+07,9.575312e+07,9.845434e+07,3,0.000067,-9.540516,False,0.000098,False,True,Human,True,False,False,True,diann231,directlfq,min,1.660964
4,P01008ups|ANT3_HUMAN_UPS,141297.235101,133796.22389,115453.070052,4.676472e+07,4.669985e+07,4.818103e+07,3,0.000105,-8.502576,False,0.000122,False,True,Human,True,False,False,True,diann231,directlfq,min,1.660964

# Testing

In [31]:
for search_dr in listdir('./search_results') :
    # print(search_dr, '\n')
    if 'LFQbench' in search_dr and not 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            cols = [colstarter+cond+'_Sample_'+s+'_'+rep+'.mzML' for cond in ['A', 'B'] for s in ['Alpha', 'Beta', 'Gamma'] for rep in ['01', '02', '03']]
            df = pd.read_csv(inpath, sep='\t', usecols=cols)
            print(search_dr, len(cols), df.isna().sum().sum(), len(df)*len(cols), round(df.isna().sum().sum()/(len(df)*len(cols)), 3))

fragpipe24_LFQbench_msfragger 18 3896 138366 0.028
fragpipe24_LFQbench_umpire 18 1795 96858 0.019
diann231_LFQbench 18 22019 163296 0.135

In [33]:
for search_dr in listdir('./search_results') :
    # print(search_dr, '\n')
    if 'LFQbench' in search_dr and 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            cols = [colstarter+cond+'_Sample_'+s+'_'+rep+'.d' for cond in ['A', 'B'] for s in ['Alpha', 'Beta', 'Gamma'] for rep in ['01', '02', '03']]
            df = pd.read_csv(inpath, sep='\t', usecols=cols)
            print(search_dr, len(cols), df.isna().sum().sum(), len(df)*len(cols), round(df.isna().sum().sum()/(len(df)*len(cols)), 3))

diann231_LFQbenchTOF 18 24614 204930 0.12
fragpipe24_LFQbenchTOF_diatracer 18 3130 187200 0.017

In [45]:
for search_dr in listdir('./search_results') :
    # print(search_dr, '\n')
    if 'ups_ecoli' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        for pair_dr in listdir(path.join('./search_results', search_dr)) :
        # pair_dr = '25fmol_vs_0_25fmol'
            if path.isdir(path.join('./search_results', search_dr, pair_dr)) and '_vs_' in pair_dr :
                conc_1, conc_2 = pair_dr.split('_vs_')
                if search_dr.startswith('fragpipe') :
                    workdir = path.join('./search_results', search_dr, pair_dr, 'dia-quant-output')
                else :
                    workdir = path.join('./search_results', search_dr, pair_dr)
                # try :
                inpath = path.join(workdir, 'report.pg_matrix.tsv')
                if path.exists(inpath) :
                    colstarter = './input_files/PXD026600/RD139_Wide_UPS1_' # 10fmol_inj2.mzML'
                    colsplitter = '_inj'
                    cols = [colstarter+cond+colsplitter+rep+'r.mzML' if cond=='10fmol' and rep=='1' else colstarter+cond+colsplitter+rep+'.mzML' for cond in [conc_1, conc_2] for rep in ['1', '2', '3']]
                    print(search_dr, pair_dr, )#cols)
                    df = pd.read_csv(inpath, sep='\t', usecols=cols)
                    print(df.isna().sum().sum(), len(df)*len(cols), round(df.isna().sum().sum()/(len(df)*len(cols)), 3))

fragpipe24_ups_ecoli_umpire 5fmol_vs_0_25fmol
127 9960 0.013
fragpipe24_ups_ecoli_umpire 25fmol_vs_2_5fmol
23 9990 0.002
fragpipe24_ups_ecoli_umpire 2_5fmol_vs_0_1fmol
69 9696 0.007
fragpipe24_ups_ecoli_umpire 25fmol_vs_1fmol
39 9942 0.004
fragpipe24_ups_ecoli_umpire 50fmol_vs_0_1fmol
111 9618 0.012
fragpipe24_ups_ecoli_umpire 25fmol_vs_0_25fmol
131 10020 0.013
fragpipe24_ups_ecoli_umpire 25fmol_vs_10fmol
23 9906 0.002
fragpipe24_ups_ecoli_umpire 50fmol_vs_10fmol
44 9858 0.004
fragpipe24_ups_ecoli_umpire 10fmol_vs_2_5fmol
45 10062 0.004
fragpipe24_ups_ecoli_umpire 50fmol_vs_25fmol
27 9804 0.003
fragpipe24_ups_ecoli_umpire 10fmol_vs_5fmol
59 9936 0.006
fragpipe24_ups_ecoli_umpire 50fmol_vs_1fmol
62 10032 0.006
fragpipe24_ups_ecoli_umpire 5fmol_vs_1fmol
66 10266 0.006
fragpipe24_ups_ecoli_umpire 1fmol_vs_0_1fmol
38 9780 0.004
fragpipe24_ups_ecoli_umpire 5fmol_vs_2_5fmol
23 9774 0.002
fragpipe24_ups_ecoli_umpire 10fmol_vs_0_25fmol
120 10098 0.012
fragpipe24_ups_ecoli_umpire 50fmol_vs_2_5fmol
40 9840 0.004
fragpipe24_ups_ecoli_umpire 10fmol_vs_0_1fmol
138 9876 0.014
fragpipe24_ups_ecoli_umpire 2_5fmol_vs_1fmol
39 10038 0.004
fragpipe24_ups_ecoli_umpire 10fmol_vs_1fmol
48 10248 0.005
fragpipe24_ups_ecoli_umpire 25fmol_vs_0_1fmol
106 9852 0.011
fragpipe24_ups_ecoli_umpire 50fmol_vs_5fmol
17 9624 0.002
fragpipe24_ups_ecoli_umpire 1fmol_vs_0_25fmol
55 9894 0.006
fragpipe24_ups_ecoli_umpire 2_5fmol_vs_0_25fmol
84 9894 0.008
fragpipe24_ups_ecoli_umpire 50fmol_vs_0_25fmol
121 9840 0.012
fragpipe24_ups_ecoli_umpire 5fmol_vs_0_1fmol
121 9852 0.012
fragpipe24_ups_ecoli_umpire 0_25fmol_vs_0_1fmol
9 9522 0.001
fragpipe24_ups_ecoli_umpire 25fmol_vs_5fmol
20 9918 0.002
fragpipe24_ups_ecoli_msfragger 2_5fmol_vs_1fmol
78 11478 0.007
fragpipe24_ups_ecoli_msfragger 0_25fmol_vs_0_1fmol
78 11208 0.007
fragpipe24_ups_ecoli_msfragger 25fmol_vs_5fmol
82 11448 0.007
fragpipe24_ups_ecoli_msfragger 2_5fmol_vs_0_25fmol
120 11430 0.01
fragpipe24_ups_ecoli_msfragger 25fmol_vs_0_25fmol
123 11526 0.011
fragpipe24_ups_ecoli_msfragger 25fmol_vs_2_5fmol
66 11502 0.006
fragpipe24_ups_ecoli_msfragger 5fmol_vs_0_25fmol
151 11388 0.013
fragpipe24_ups_ecoli_msfragger 5fmol_vs_1fmol
79 11352 0.007
fragpipe24_ups_ecoli_msfragger 5fmol_vs_0_1fmol
144 11364 0.013
fragpipe24_ups_ecoli_msfragger 50fmol_vs_0_1fmol
188 11550 0.016
fragpipe24_ups_ecoli_msfragger 2_5fmol_vs_0_1fmol
145 11418 0.013
fragpipe24_ups_ecoli_msfragger 10fmol_vs_2_5fmol
57 11394 0.005
fragpipe24_ups_ecoli_msfragger 10fmol_vs_1fmol
82 11544 0.007
fragpipe24_ups_ecoli_msfragger 50fmol_vs_5fmol
44 11250 0.004
fragpipe24_ups_ecoli_msfragger 10fmol_vs_5fmol
63 11484 0.005
fragpipe24_ups_ecoli_msfragger 50fmol_vs_1fmol
123 11580 0.011
fragpipe24_ups_ecoli_msfragger 50fmol_vs_10fmol
116 11574 0.01
fragpipe24_ups_ecoli_msfragger 25fmol_vs_10fmol
56 11514 0.005
fragpipe24_ups_ecoli_msfragger 50fmol_vs_0_25fmol
145 11484 0.013
fragpipe24_ups_ecoli_msfragger 50fmol_vs_25fmol
84 11568 0.007
fragpipe24_ups_ecoli_msfragger 50fmol_vs_2_5fmol
120 11526 0.01
fragpipe24_ups_ecoli_msfragger 25fmol_vs_1fmol
74 11586 0.006
fragpipe24_ups_ecoli_msfragger 10fmol_vs_0_1fmol
136 11526 0.012
fragpipe24_ups_ecoli_msfragger 10fmol_vs_0_25fmol
132 11490 0.011
fragpipe24_ups_ecoli_msfragger 25fmol_vs_0_1fmol
127 11448 0.011
fragpipe24_ups_ecoli_msfragger 5fmol_vs_2_5fmol
75 11304 0.007
fragpipe24_ups_ecoli_msfragger 1fmol_vs_0_25fmol
98 11310 0.009
fragpipe24_ups_ecoli_msfragger 1fmol_vs_0_1fmol
119 11358 0.01
diann231_ups_ecoli 50fmol_vs_0_25fmol
507 11808 0.043
diann231_ups_ecoli 25fmol_vs_1fmol
393 11826 0.033
diann231_ups_ecoli 5fmol_vs_0_1fmol
542 11868 0.046
diann231_ups_ecoli 50fmol_vs_2_5fmol
442 11568 0.038
diann231_ups_ecoli 10fmol_vs_5fmol
372 11736 0.032
diann231_ups_ecoli 50fmol_vs_1fmol
493 11676 0.042
diann231_ups_ecoli 2_5fmol_vs_1fmol
416 11658 0.036
diann231_ups_ecoli 10fmol_vs_0_1fmol
489 11874 0.041
diann231_ups_ecoli 10fmol_vs_0_25fmol
487 11910 0.041
diann231_ups_ecoli 5fmol_vs_1fmol
429 11862 0.036
diann231_ups_ecoli 25fmol_vs_0_1fmol
424 11856 0.036
diann231_ups_ecoli 1fmol_vs_0_25fmol
375 11700 0.032
diann231_ups_ecoli 0_25fmol_vs_0_1fmol
304 11520 0.026
diann231_ups_ecoli 10fmol_vs_1fmol
366 11730 0.031
diann231_ups_ecoli 50fmol_vs_5fmol
331 11664 0.028
diann231_ups_ecoli 5fmol_vs_2_5fmol
384 11754 0.033
diann231_ups_ecoli 1fmol_vs_0_1fmol
354 11658 0.03
diann231_ups_ecoli 2_5fmol_vs_0_25fmol
384 11652 0.033
diann231_ups_ecoli 25fmol_vs_2_5fmol
395 11766 0.034
diann231_ups_ecoli 5fmol_vs_0_25fmol
471 11766 0.04
diann231_ups_ecoli 2_5fmol_vs_0_1fmol
433 11784 0.037
diann231_ups_ecoli 50fmol_vs_0_1fmol
499 11742 0.042
diann231_ups_ecoli 50fmol_vs_10fmol
444 11592 0.038
diann231_ups_ecoli 25fmol_vs_10fmol
376 11772 0.032
diann231_ups_ecoli 25fmol_vs_5fmol
345 11790 0.029
diann231_ups_ecoli 25fmol_vs_0_25fmol
422 11880 0.036
diann231_ups_ecoli 10fmol_vs_2_5fmol
437 11820 0.037
diann231_ups_ecoli 50fmol_vs_25fmol
441 11700 0.038

# Flow run

## AlphaPeptStats LFQbench orbitrap imputation RandomForest

In [22]:
imputation = 'knn'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and not 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr and 'diann231' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(workdir, 'quant_alphastats_{}.tsv'.format(imputation))
            try :
                se = search_dr.split('LFQbench')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            de, h_de, e_de, y_de, lfq_df = alpha_quant(inpath, 
                                            colstarter=colstarter, 
                                            colsplitter=colsplitter, 
                                            condstarter='Condition_',
                                            organism_dict=lfqbench_organism_dict, 
                                            imputation=imputation, 
                                            # max_nan=9,
                                            min_fc=0.5, 
                                            search_engine=se, 
                                            # quant='manual',
                                            save_path=save_path)
            print('AlphaStats', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

2026-08-13 15:09:34,925 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-13 15:09:34,930 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-13 15:09:34,958 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 8 observations have been removed.
2026-08-13 15:09:34,960 - root - INFO - Imputing data...

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

fragpipe24_LFQbench_msfragger

fragpipe24_LFQbenchTOF_diatracer_triqler

diann181_ups_ecoli_pg_intensities

tmp

fragpipe24_LFQbench_umpire

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

diann231_25fmol_vs_5fmol_rerun

fragpipe24_LFQbench.sh

diann231_LFQbench

Data columns: ['Protein.Group', 'Protein.Names', 'Genes', 'First.Protein.Description', 'N.Sequences_Intensity', 'N.Proteotypic.Sequences_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML_Intensity', 'contamination_library']
Metadata sample names: ['LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML']
DataSet has been created.
AlphaStats diann231_LFQbench done

fragpipe24_ups_ecoli_umpire_triqler

fragpipe24_ups_ecoli_msfragger

diann231_ups_ecoli

fragpipe24_UPS-Ecoli.sh

## AlphaPeptStats LFQbench orbitrap imputation RandomForest

In [ ]:
imputation = 'randomforest'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and not 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(workdir, 'quant_alphastats_{}.tsv'.format(imputation))
            try :
                se = search_dr.split('LFQbench')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            de, h_de, e_de, y_de, lfq_df = alpha_quant(inpath, 
                                            colstarter=colstarter, 
                                            colsplitter=colsplitter, 
                                            condstarter='Condition_',
                                            organism_dict=lfqbench_organism_dict, 
                                            imputation=imputation, 
                                            # max_nan=9,
                                            min_fc=0.5, 
                                            search_engine=se, 
                                            # quant='manual',
                                            save_path=save_path)
            print('AlphaStats', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

2026-07-29 18:45:56,420 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-07-29 18:45:56,427 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-07-29 18:45:56,455 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 9 observations have been removed.
2026-07-29 18:45:56,457 - root - INFO - Imputing data...

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

fragpipe24_LFQbench_msfragger

Data columns: ['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML_Intensity', 'contamination_library']
Metadata sample names: ['LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML']
DataSet has been created.
[IterativeImputer] Completing matrix with shape (18, 7678)

## AlphaPeptStats LFQbench orbitrap imputation mean

In [ ]:
imputation = 'mean'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and not 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(workdir, 'quant_alphastats_{}.tsv'.format(imputation))
            try :
                se = search_dr.split('LFQbench')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            de, h_de, e_de, y_de, lfq_df = alpha_quant(inpath, 
                                            colstarter=colstarter, 
                                            colsplitter=colsplitter, 
                                            condstarter='Condition_',
                                            organism_dict=lfqbench_organism_dict, 
                                            imputation=imputation, 
                                            # max_nan=9,
                                            min_fc=0.5, 
                                            search_engine=se, 
                                            # quant='manual',
                                            save_path=save_path)
            print('AlphaStats', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

2026-07-29 18:45:56,420 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-07-29 18:45:56,427 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-07-29 18:45:56,455 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 9 observations have been removed.
2026-07-29 18:45:56,457 - root - INFO - Imputing data...

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

fragpipe24_LFQbench_msfragger

Data columns: ['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML_Intensity', 'contamination_library']
Metadata sample names: ['LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML']
DataSet has been created.
[IterativeImputer] Completing matrix with shape (18, 7678)

## AlphaPeptStats LFQbench orbitrap imputation None

In [14]:
imputation = None
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and not 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(workdir, 'quant_alphastats_{}.tsv'.format(imputation))
            try :
                se = search_dr.split('LFQbench')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            de, h_de, e_de, y_de, lfq_df = alpha_quant(inpath, 
                                            colstarter=colstarter, 
                                            colsplitter=colsplitter, 
                                            condstarter='Condition_',
                                            organism_dict=lfqbench_organism_dict, 
                                            imputation=imputation, 
                                            # max_nan=9,
                                            min_fc=0.5, 
                                            search_engine=se, 
                                            # quant='manual',
                                            save_path=save_path)
            print('AlphaStats', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

2026-08-13 14:16:42,334 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-13 14:16:42,340 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-13 14:16:42,365 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 9 observations have been removed.

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

fragpipe24_LFQbench_msfragger

Data columns: ['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML_Intensity', 'contamination_library']
Metadata sample names: ['LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML']
DataSet has been created.

2026-08-13 14:16:51,948 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-13 14:16:51,953 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full

AlphaStats fragpipe24_LFQbench_msfragger done

fragpipe24_LFQbenchTOF_diatracer_triqler

diann181_ups_ecoli_pg_intensities

tmp

fragpipe24_LFQbench_umpire

Data columns: ['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML_Intensity', 'contamination_library']
Metadata sample names: ['LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML']

2026-08-13 14:16:52,132 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 7 observations have been removed.

DataSet has been created.

2026-08-13 14:16:58,322 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-13 14:16:58,328 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-13 14:16:58,358 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 8 observations have been removed.

AlphaStats fragpipe24_LFQbench_umpire done

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

diann231_25fmol_vs_5fmol_rerun

fragpipe24_LFQbench.sh

diann231_LFQbench

Data columns: ['Protein.Group', 'Protein.Names', 'Genes', 'First.Protein.Description', 'N.Sequences_Intensity', 'N.Proteotypic.Sequences_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML_Intensity', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML_Intensity', 'contamination_library']
Metadata sample names: ['LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML']
DataSet has been created.
AlphaStats diann231_LFQbench done

fragpipe24_ups_ecoli_umpire_triqler

fragpipe24_ups_ecoli_msfragger

diann231_ups_ecoli

fragpipe24_UPS-Ecoli.sh

## AlphaPeptStats UPS-Ecoli

In [14]:
imputation = 'randomforest'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'ups_ecoli' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        for pair_dr in listdir(path.join('./search_results', search_dr)) :
            if path.isdir(path.join('./search_results', search_dr, pair_dr)) and '_vs_' in pair_dr :
                conc_1, conc_2 = pair_dr.replace('fmol', '').split('_vs_')
                min_fc = 0.5*np.log2(min(float(conc_1.replace('_', '.'))/float(conc_2.replace('_', '.')), 10))
                if search_dr.startswith('fragpipe') :
                    workdir = path.join('./search_results', search_dr, pair_dr, 'dia-quant-output')
                else :
                    workdir = path.join('./search_results', search_dr, pair_dr)
                # try :
                inpath = path.join(workdir, 'report.pg_matrix.tsv')
                if path.exists(inpath) :
                    colstarter = '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_' # 10fmol_inj2.mzML'
                    colsplitter = 'inj'
                    save_path = path.join(workdir, 'quant_alphastats_{}.tsv'.format(imputation))
                    try :
                        se = search_dr.split('ups_ecoli')[-1].split('_')[1]
                    except :
                        se = search_dr.split('_')[0]
                    de, h_de, e_de, y_de, lfq_df = alpha_quant(inpath, 
                                                                colstarter=colstarter, 
                                                                colsplitter=colsplitter, 
                                                                condstarter='',
                                                                organism_dict=ups_ecoli_organism_dict, 
                                                                imputation=imputation, 
                                                                min_fc=min_fc, 
                                                                search_engine=se, 
                                                                save_path=save_path)
                    print('AlphaStats', search_dr, 'done\n')
                else :
                    print('no input file in', search_dr)

2026-07-30 13:07:16,589 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-07-30 13:07:16,598 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-07-30 13:07:16,615 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 0 observations have been removed.
2026-07-30 13:07:16,617 - root - INFO - Imputing data...

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

Data columns: ['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', 'RD139_Wide_UPS1_5fmol_inj2.mzML_Intensity', 'RD139_Wide_UPS1_5fmol_inj1.mzML_Intensity', 'RD139_Wide_UPS1_0_25fmol_inj2.mzML_Intensity', 'RD139_Wide_UPS1_5fmol_inj3.mzML_Intensity', 'RD139_Wide_UPS1_0_25fmol_inj3.mzML_Intensity', 'RD139_Wide_UPS1_0_25fmol_inj1.mzML_Intensity', 'contamination_library']
Metadata sample names: ['RD139_Wide_UPS1_0_25fmol_inj1.mzML', 'RD139_Wide_UPS1_0_25fmol_inj2.mzML', 'RD139_Wide_UPS1_0_25fmol_inj3.mzML', 'RD139_Wide_UPS1_5fmol_inj1.mzML', 'RD139_Wide_UPS1_5fmol_inj2.mzML', 'RD139_Wide_UPS1_5fmol_inj3.mzML']
DataSet has been created.
[IterativeImputer] Completing matrix with shape (6, 1660)
[IterativeImputer] Change: 0.0, scaled tolerance: 1512350.0
[IterativeImputer] Early stopping criterion reached.

2026-07-30 13:31:34,481 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-07-30 13:31:34,485 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-07-30 13:31:34,496 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 0 observations have been removed.
2026-07-30 13:31:34,498 - root - INFO - Imputing data...

AlphaStats fragpipe24_ups_ecoli_umpire done

Data columns: ['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', 'RD139_Wide_UPS1_25fmol_inj1.mzML_Intensity', 'RD139_Wide_UPS1_25fmol_inj3.mzML_Intensity', 'RD139_Wide_UPS1_25fmol_inj2.mzML_Intensity', 'RD139_Wide_UPS1_2_5fmol_inj3.mzML_Intensity', 'RD139_Wide_UPS1_2_5fmol_inj1.mzML_Intensity', 'RD139_Wide_UPS1_2_5fmol_inj2.mzML_Intensity', 'contamination_library']
Metadata sample names: ['RD139_Wide_UPS1_2_5fmol_inj1.mzML', 'RD139_Wide_UPS1_2_5fmol_inj2.mzML', 'RD139_Wide_UPS1_2_5fmol_inj3.mzML', 'RD139_Wide_UPS1_25fmol_inj1.mzML', 'RD139_Wide_UPS1_25fmol_inj2.mzML', 'RD139_Wide_UPS1_25fmol_inj3.mzML']
DataSet has been created.
[IterativeImputer] Completing matrix with shape (6, 1665)

KeyboardInterrupt:

In [ ]:
conc_1, conc_2 = pair_dr.replace('fmol', '').split('_vs_')
min_fc = 0.5*np.log2(min(float(conc_1.replace('_', '.'))/float(conc_2.replace('_', '.')), 10))

## Manual UPS-Ecoli

In [44]:
imputation = 'min'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'ups_ecoli' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        for pair_dr in listdir(path.join('./search_results', search_dr)) :
            if path.isdir(path.join('./search_results', search_dr, pair_dr)) and '_vs_' in pair_dr :
                conc_1, conc_2 = pair_dr.replace('fmol', '').split('_vs_')
                min_fc = 0.5*np.log2(min(float(conc_1.replace('_', '.'))/float(conc_2.replace('_', '.')), 10))
                if search_dr.startswith('fragpipe') :
                    workdir = path.join('./search_results', search_dr, pair_dr, 'dia-quant-output')
                else :
                    workdir = path.join('./search_results', search_dr, pair_dr)
                inpath = path.join(workdir, 'report.pg_matrix.tsv')
                if path.exists(inpath) :
                    colstarter = './input_files/PXD026600/RD139_Wide_UPS1_' # 10fmol_inj2.mzML'
                    colsplitter = 'inj'
                    save_path = path.join(workdir, 'quant_manual_{}.tsv'.format(imputation))
                    try :
                        se = search_dr.split('ups_ecoli')[-1].split('_')[1]
                    except :
                        se = search_dr.split('_')[0]
                    de, h_de, e_de, y_de, lfq_df = manual_quant(inpath, 
                                                                colstarter=colstarter, 
                                                                colsplitter=colsplitter, 
                                                                condstarter='',
                                                                organism_dict=ups_ecoli_organism_dict, 
                                                                imputation=imputation, 
                                                                min_fc=min_fc, 
                                                                search_engine=se, 
                                                                quant='manual',
                                                                save_path=save_path)
                    print('manual', search_dr, pair_dr, 'done\n')
                else :
                    print('no input file in', search_dr, pair_dr,)

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 5fmol_vs_0_25fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj2.mzML']
manual fragpipe24_ups_ecoli_umpire 25fmol_vs_2_5fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 2_5fmol_vs_0_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 25fmol_vs_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj3.mzML']
manual fragpipe24_ups_ecoli_umpire 50fmol_vs_0_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 25fmol_vs_0_25fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj1r.mzML']
manual fragpipe24_ups_ecoli_umpire 25fmol_vs_10fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj1r.mzML']
manual fragpipe24_ups_ecoli_umpire 50fmol_vs_10fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj1r.mzML']
manual fragpipe24_ups_ecoli_umpire 10fmol_vs_2_5fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj3.mzML']
manual fragpipe24_ups_ecoli_umpire 50fmol_vs_25fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj1r.mzML']
manual fragpipe24_ups_ecoli_umpire 10fmol_vs_5fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj3.mzML']
manual fragpipe24_ups_ecoli_umpire 50fmol_vs_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 5fmol_vs_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 1fmol_vs_0_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj2.mzML']
manual fragpipe24_ups_ecoli_umpire 5fmol_vs_2_5fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj1r.mzML']
manual fragpipe24_ups_ecoli_umpire 10fmol_vs_0_25fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj3.mzML']
manual fragpipe24_ups_ecoli_umpire 50fmol_vs_2_5fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj1r.mzML']
manual fragpipe24_ups_ecoli_umpire 10fmol_vs_0_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 2_5fmol_vs_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_10fmol_inj1r.mzML']
manual fragpipe24_ups_ecoli_umpire 10fmol_vs_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 25fmol_vs_0_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj3.mzML']
manual fragpipe24_ups_ecoli_umpire 50fmol_vs_5fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 1fmol_vs_0_25fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_2_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 2_5fmol_vs_0_25fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_50fmol_inj3.mzML']
manual fragpipe24_ups_ecoli_umpire 50fmol_vs_0_25fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 5fmol_vs_0_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_0_1fmol_inj1.mzML']
manual fragpipe24_ups_ecoli_umpire 0_25fmol_vs_0_1fmol done

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj2.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj1.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_5fmol_inj3.mzML', '/home/lerost/DIA_tools_manuscript/input_files/PXD026600/RD139_Wide_UPS1_25fmol_inj2.mzML']
manual fragpipe24_ups_ecoli_umpire 25fmol_vs_5fmol done

fragpipe24_LFQbenchTOF_diatracer

fragpipe24_LFQbench_msfragger

fragpipe24_LFQbenchTOF_diatracer_triqler

tmp

fragpipe24_LFQbench_umpire

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

fragpipe24_LFQbench.sh


## Manual LFQbench orbitrap

In [69]:
imputation = 'min'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and not 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(workdir, 'quant_manual_{}.tsv'.format(imputation))
            try :
                se = search_dr.split('LFQbench')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            de, h_de, e_de, y_de, lfq_df = manual_quant(inpath, 
                                                        colstarter=colstarter, 
                                                        colsplitter=colsplitter, 
                                                        condstarter='Condition_',
                                                        organism_dict=lfqbench_organism_dict, 
                                                        imputation=imputation, 
                                                        max_nan=9,
                                                        min_fc=0.5, 
                                                        search_engine=se, 
                                                        quant='manual',
                                                        save_path=save_path)
            print('manual', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

fragpipe24_LFQbench_msfragger

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML']
manual fragpipe24_LFQbench_msfragger done

fragpipe24_LFQbenchTOF_diatracer_triqler

tmp

fragpipe24_LFQbench_umpire

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML']
manual fragpipe24_LFQbench_umpire done

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

fragpipe24_LFQbench.sh

diann231_LFQbench

['Protein.Group', 'Protein.Names', 'Genes', 'First.Protein.Description', 'N.Sequences', 'N.Proteotypic.Sequences', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02.mzML', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_orbitrap/LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03.mzML']
manual diann231_LFQbench done

fragpipe24_ups_ecoli_umpire_triqler

fragpipe24_ups_ecoli_msfragger

diann231_ups_ecoli

fragpipe24_UPS-Ecoli.sh

## Generate directLFQ intensities

In [ ]:
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            inpath = path.join('./search_results', search_dr, 'dia-quant-output', 'report.tsv')
        else :
            inpath = path.join('./search_results', search_dr, 'report.parquet')
        # inpath = path.join(workdir, 'report.parquet')
        lfq_manager.run_lfq(inpath, columns_to_add=['Protein.Group', 'Protein.Ids'])

In [ ]:
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'ups_ecoli' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        for comp in listdir(path.join('./search_results', search_dr)) :
            if '_vs_' in comp : 
                if search_dr.startswith('fragpipe') :
                    inpath = path.join('./search_results', search_dr, comp, 'dia-quant-output', 'report.tsv')
                else :
                    inpath = path.join('./search_results', search_dr, comp, 'report.parquet')
                # inpath = path.join(workdir, 'report.parquet')
                lfq_manager.run_lfq(inpath, columns_to_add=['Protein.Group', 'Protein.Ids'])

## directLFQ p-value estimation UPS-Ecoli

In [60]:
conc_1 = '0_25'
conc_2 = '25'
0.5*np.log2(min(abs(float(conc_1.replace('_', '.'))/float(conc_2.replace('_', '.'))), 10)), 0.5*np.log2(10)

(-3.321928094887362, 1.660964047443681)

In [46]:
imputation = 'min'
quant = 'directlfq'

for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'ups_ecoli' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        for pair_dr in listdir(path.join('./search_results', search_dr)) :
            if path.isdir(path.join('./search_results', search_dr, pair_dr)) and '_vs_' in pair_dr :
                conc_1, conc_2 = pair_dr.replace('fmol', '').split('_vs_')
                min_fc = 0.5*np.log2(min(float(conc_1.replace('_', '.'))/float(conc_2.replace('_', '.')), 10))
                if search_dr.startswith('fragpipe') :
                    inpath = path.join('./search_results', search_dr, pair_dr, 'dia-quant-output', 'report.tsv.protein_intensities.tsv')
                    prot_col=''
                else :
                    inpath = path.join('./search_results', search_dr, pair_dr, 'report.parquet.protein_intensities.tsv')
                    prot_col='protein'
                if path.exists(inpath) :
                    colstarter = 'RD139_Wide_UPS1_' # 10fmol_inj2.mzML'
                    colsplitter = 'inj'
                    save_path = path.join(path.dirname(inpath), 'quant_{}_{}.tsv'.format(quant, imputation))
                    try :
                        se = search_dr.split('ups_ecoli')[-1].split('_')[1]
                    except :
                        se = search_dr.split('_')[0]
                    de, h_de, e_de, y_de, lfq_df = manual_quant(inpath, 
                                                                colstarter=colstarter, 
                                                                colsplitter=colsplitter, 
                                                                condstarter='',
                                                                organism_dict=ups_ecoli_organism_dict, 
                                                                prot_col=prot_col,
                                                                imputation=imputation, 
                                                                min_fc=min_fc, 
                                                                search_engine=se, 
                                                                quant=quant,
                                                                save_path=save_path)
                    print('manual', search_dr, 'done\n')
                else :
                    print('no input file in', search_dr)

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

['protein', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_umpire done

fragpipe24_LFQbenchTOF_diatracer

fragpipe24_LFQbench_msfragger

fragpipe24_LFQbenchTOF_diatracer_triqler

tmp

fragpipe24_LFQbench_umpire

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

fragpipe24_LFQbench.sh

diann231_LFQbench

fragpipe24_ups_ecoli_umpire_triqler

fragpipe24_ups_ecoli_msfragger

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_ups_ecoli_msfragger done

diann231_ups_ecoli

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_50fmol_inj1', 'RD139_Wide_UPS1_50fmol_inj2', 'RD139_Wide_UPS1_50fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_2_5fmol_inj1', 'RD139_Wide_UPS1_2_5fmol_inj2', 'RD139_Wide_UPS1_2_5fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_0_25fmol_inj1', 'RD139_Wide_UPS1_0_25fmol_inj2', 'RD139_Wide_UPS1_0_25fmol_inj3', 'RD139_Wide_UPS1_10fmol_inj1r', 'RD139_Wide_UPS1_10fmol_inj2', 'RD139_Wide_UPS1_10fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_1fmol_inj1', 'RD139_Wide_UPS1_1fmol_inj2', 'RD139_Wide_UPS1_1fmol_inj3', 'RD139_Wide_UPS1_5fmol_inj1', 'RD139_Wide_UPS1_5fmol_inj2', 'RD139_Wide_UPS1_5fmol_inj3']
manual diann231_ups_ecoli done

['protein', 'RD139_Wide_UPS1_0_1fmol_inj1', 'RD139_Wide_UPS1_0_1fmol_inj2', 'RD139_Wide_UPS1_0_1fmol_inj3', 'RD139_Wide_UPS1_25fmol_inj1', 'RD139_Wide_UPS1_25fmol_inj2', 'RD139_Wide_UPS1_25fmol_inj3']
manual diann231_ups_ecoli done


## directLFQ p-value estimation LFQbench Orbitrap

In [47]:
imputation = 'min'
quant = 'directlfq'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and not 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            inpath = path.join('./search_results', search_dr, 'dia-quant-output', 'report.tsv.protein_intensities.tsv')
            prot_col=''
        else :
            inpath = path.join('./search_results', search_dr, 'report.parquet.protein_intensities.tsv')
            prot_col=''
        if path.exists(inpath) :
            colstarter = 'LFQ_Orbitrap_AIF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(path.dirname(inpath), 'quant_{}_{}.tsv'.format(quant, imputation))
            print(save_path)
            try :
                se = search_dr.split('LFQbench')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            de, h_de, e_de, y_de, lfq_df = manual_quant(inpath, 
                                                        colstarter=colstarter, 
                                                        colsplitter=colsplitter, 
                                                        condstarter='Condition_',
                                                        organism_dict=lfqbench_organism_dict, 
                                                        prot_col=prot_col,
                                                        imputation=imputation, 
                                                        max_nan=9,
                                                        min_fc=0.5, 
                                                        search_engine=se, 
                                                        quant=quant,
                                                        save_path=save_path)
            print('manual', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

diann231_LFQbenchTOF

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

fragpipe24_LFQbench_msfragger

./search_results/fragpipe24_LFQbench_msfragger/dia-quant-output/quant_directlfq_min.tsv
['protein', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_LFQbench_msfragger done

fragpipe24_LFQbenchTOF_diatracer_triqler

tmp

fragpipe24_LFQbench_umpire

./search_results/fragpipe24_LFQbench_umpire/dia-quant-output/quant_directlfq_min.tsv
['protein', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_LFQbench_umpire done

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

fragpipe24_LFQbench.sh

diann231_LFQbench

./search_results/diann231_LFQbench/quant_directlfq_min.tsv
['protein', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_03', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Beta_03', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_01', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_02', 'LFQ_Orbitrap_AIF_Condition_A_Sample_Gamma_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Alpha_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Beta_03', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_01', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_02', 'LFQ_Orbitrap_AIF_Condition_B_Sample_Gamma_03', 'Protein.Ids', 'Protein.Group']
manual diann231_LFQbench done

fragpipe24_ups_ecoli_umpire_triqler

fragpipe24_ups_ecoli_msfragger

diann231_ups_ecoli

fragpipe24_UPS-Ecoli.sh

In [ ]:
tdf = pd.read_parquet('./search_results/diann231_LFQbench/report.parquet', )
ttdf = pd.read_csv('./search_results/diann231_LFQbench/report.parquet.protein_intensities.tsv', sep='\t')
exclude = ['Protein.Group', 'Protein.Ids', 'Protein.Ids_x', 'Protein.Ids_y']
cols = [col for col in ttdf.columns if not col in exclude]
ttdf = ttdf[cols].copy()
print(len(tdf), len(ttdf))
tdf = tdf.sort_values('Global.PG.Q.Value')[['Protein.Ids', 'Protein.Group']].drop_duplicates().drop_duplicates(subset=['Protein.Ids']).copy()
ttdf = ttdf.merge(tdf, how='left', left_on='protein', right_on='Protein.Ids')
print(len(tdf), len(ttdf))
ttdf = ttdf.dropna(subset=['Protein.Group'])
print(ttdf['Protein.Group'].isna().sum(), len(ttdf), len(ttdf[ttdf['protein'].map(lambda x: ';' in x)]), len(ttdf[(ttdf['protein'].map(lambda x: ';' in x)) & (ttdf['Protein.Group'].isna())]))
ttdf.head()
ttdf.to_csv('./search_results/diann231_LFQbench/report.parquet.protein_intensities.tsv', sep='\t', index=False)

## AlphaPeptStats LFQbench Bruker timsTOF

In [ ]:
imputation = 'randomforest'
# imputation = 'mean'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(workdir, 'quant_alphastats_{}.tsv'.format(imputation))
            try :
                se = search_dr.split('LFQbench')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            de, h_de, e_de, y_de, lfq_df = alpha_quant(inpath, 
                                            colstarter=colstarter, 
                                            colsplitter=colsplitter, 
                                            condstarter='Condition_',
                                            organism_dict=lfqbench_organism_dict, 
                                            imputation=imputation, 
                                            # max_nan=9,
                                            min_fc=0.5, 
                                            search_engine=se, 
                                            # quant='manual',
                                            save_path=save_path)
            print('AlphaStats', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

2026-08-03 17:08:43,543 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-03 17:08:43,549 - root - INFO - Column 'contamination_library' has been added, to indicate contaminations.
The contaminant library was created by Frankenfield et al.:https://www.biorxiv.org/content/10.1101/2022.04.27.489766v2.full
2026-08-03 17:08:43,584 - root - INFO - Contaminations indicated in following columns: ['contamination_library', 'contamination_library'] were removed. In total 11 observations have been removed.
2026-08-03 17:08:43,586 - root - INFO - Imputing data...

diann231_LFQbenchTOF

Data columns: ['Protein.Group', 'Protein.Names', 'Genes', 'First.Protein.Description', 'N.Sequences_Intensity', 'N.Proteotypic.Sequences_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_01.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_03.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_01.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_02.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_03.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_01.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_02.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_03.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_01.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_02.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_03.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_01.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_02.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_03.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_01.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_02.d_Intensity', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_03.d_Intensity', 'contamination_library']
Metadata sample names: ['LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_01.d', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02.d', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_03.d', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_01.d', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_02.d', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_03.d', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_01.d', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_02.d', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_03.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_01.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_02.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_03.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_01.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_02.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_03.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_01.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_02.d', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_03.d']
DataSet has been created.
[IterativeImputer] Completing matrix with shape (18, 11374)

## Generate directLFQ intensities for timsTOF

In [61]:
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            inpath = path.join('./search_results', search_dr, 'dia-quant-output', 'report.tsv')
        else :
            inpath = path.join('./search_results', search_dr, 'report.parquet')
        # inpath = path.join(workdir, 'report.parquet')
        lfq_manager.run_lfq(inpath, columns_to_add=['Protein.Group', 'Protein.Ids'])

2026-08-03 16:50:18,255 - directlfq.lfq_manager - INFO - Starting directLFQ analysis.

diann231_LFQbenchTOF

2026-08-03 16:50:18,573 - directlfq.utils - INFO - using input type diann_precursors
2026-08-03 16:50:22,472 - directlfq.lfq_manager - INFO - Performing sample normalization.
2026-08-03 16:50:25,149 - directlfq.lfq_manager - INFO - Estimating lfq intensities.
2026-08-03 16:50:25,160 - directlfq.protein_intensity_estimation - INFO - 15207 lfq-groups total
2026-08-03 16:50:35,450 - directlfq.protein_intensity_estimation - INFO - using 60 processes
2026-08-03 16:50:35,570 - directlfq.protein_intensity_estimation - INFO - lfq-object 0
2026-08-03 16:50:36,002 - directlfq.protein_intensity_estimation - INFO - lfq-object 200
2026-08-03 16:50:36,013 - directlfq.protein_intensity_estimation - INFO - lfq-object 100
2026-08-03 16:50:36,208 - directlfq.protein_intensity_estimation - INFO - lfq-object 700
2026-08-03 16:50:36,238 - directlfq.protein_intensity_estimation - INFO - lfq-object 500
2026-08-03 16:50:36,301 - directlfq.protein_intensity_estimation - INFO - lfq-object 300
2026-08-03 16:50:36,461 - directlfq.protein_intensity_estimation - INFO - lfq-object 400
2026-08-03 16:50:36,638 - directlfq.protein_intensity_estimation - INFO - lfq-object 600
2026-08-03 16:50:36,887 - directlfq.protein_intensity_estimation - INFO - lfq-object 800
2026-08-03 16:50:36,935 - directlfq.protein_intensity_estimation - INFO - lfq-object 1400
2026-08-03 16:50:36,993 - directlfq.protein_intensity_estimation - INFO - lfq-object 1200
2026-08-03 16:50:36,996 - directlfq.protein_intensity_estimation - INFO - lfq-object 1000
2026-08-03 16:50:37,137 - directlfq.protein_intensity_estimation - INFO - lfq-object 1300
2026-08-03 16:50:37,208 - directlfq.protein_intensity_estimation - INFO - lfq-object 1100
2026-08-03 16:50:37,332 - directlfq.protein_intensity_estimation - INFO - lfq-object 900
2026-08-03 16:50:37,599 - directlfq.protein_intensity_estimation - INFO - lfq-object 1500
2026-08-03 16:50:37,646 - directlfq.protein_intensity_estimation - INFO - lfq-object 1700
2026-08-03 16:50:37,778 - directlfq.protein_intensity_estimation - INFO - lfq-object 1900
2026-08-03 16:50:37,917 - directlfq.protein_intensity_estimation - INFO - lfq-object 2100
2026-08-03 16:50:38,041 - directlfq.protein_intensity_estimation - INFO - lfq-object 1600
2026-08-03 16:50:38,148 - directlfq.protein_intensity_estimation - INFO - lfq-object 2000
2026-08-03 16:50:38,167 - directlfq.protein_intensity_estimation - INFO - lfq-object 1800
2026-08-03 16:50:38,417 - directlfq.protein_intensity_estimation - INFO - lfq-object 2200
2026-08-03 16:50:38,496 - directlfq.protein_intensity_estimation - INFO - lfq-object 2400
2026-08-03 16:50:38,583 - directlfq.protein_intensity_estimation - INFO - lfq-object 2300
2026-08-03 16:50:38,749 - directlfq.protein_intensity_estimation - INFO - lfq-object 2500
2026-08-03 16:50:38,865 - directlfq.protein_intensity_estimation - INFO - lfq-object 2600
2026-08-03 16:50:39,201 - directlfq.protein_intensity_estimation - INFO - lfq-object 2700
2026-08-03 16:50:39,830 - directlfq.protein_intensity_estimation - INFO - lfq-object 2800
2026-08-03 16:50:40,561 - directlfq.protein_intensity_estimation - INFO - lfq-object 3100
2026-08-03 16:50:40,650 - directlfq.protein_intensity_estimation - INFO - lfq-object 2900
2026-08-03 16:50:40,690 - directlfq.protein_intensity_estimation - INFO - lfq-object 3500
2026-08-03 16:50:40,792 - directlfq.protein_intensity_estimation - INFO - lfq-object 3300
2026-08-03 16:50:41,080 - directlfq.protein_intensity_estimation - INFO - lfq-object 3200
2026-08-03 16:50:41,144 - directlfq.protein_intensity_estimation - INFO - lfq-object 3000
2026-08-03 16:50:41,206 - directlfq.protein_intensity_estimation - INFO - lfq-object 3600
2026-08-03 16:50:41,230 - directlfq.protein_intensity_estimation - INFO - lfq-object 3400
2026-08-03 16:50:41,330 - directlfq.protein_intensity_estimation - INFO - lfq-object 3800
2026-08-03 16:50:41,423 - directlfq.protein_intensity_estimation - INFO - lfq-object 3700
2026-08-03 16:50:41,497 - directlfq.protein_intensity_estimation - INFO - lfq-object 4200
2026-08-03 16:50:41,579 - directlfq.protein_intensity_estimation - INFO - lfq-object 4000
2026-08-03 16:50:41,732 - directlfq.protein_intensity_estimation - INFO - lfq-object 3900
2026-08-03 16:50:41,944 - directlfq.protein_intensity_estimation - INFO - lfq-object 4100
2026-08-03 16:50:41,972 - directlfq.protein_intensity_estimation - INFO - lfq-object 4300
2026-08-03 16:50:42,341 - directlfq.protein_intensity_estimation - INFO - lfq-object 4500
2026-08-03 16:50:42,496 - directlfq.protein_intensity_estimation - INFO - lfq-object 4700
2026-08-03 16:50:42,635 - directlfq.protein_intensity_estimation - INFO - lfq-object 4400
2026-08-03 16:50:42,754 - directlfq.protein_intensity_estimation - INFO - lfq-object 4900
2026-08-03 16:50:42,889 - directlfq.protein_intensity_estimation - INFO - lfq-object 4600
2026-08-03 16:50:42,975 - directlfq.protein_intensity_estimation - INFO - lfq-object 4800
2026-08-03 16:50:42,993 - directlfq.protein_intensity_estimation - INFO - lfq-object 5000
2026-08-03 16:50:43,366 - directlfq.protein_intensity_estimation - INFO - lfq-object 5200
2026-08-03 16:50:43,409 - directlfq.protein_intensity_estimation - INFO - lfq-object 5100
2026-08-03 16:50:43,444 - directlfq.protein_intensity_estimation - INFO - lfq-object 5300
2026-08-03 16:50:43,524 - directlfq.protein_intensity_estimation - INFO - lfq-object 5400
2026-08-03 16:50:43,714 - directlfq.protein_intensity_estimation - INFO - lfq-object 5600
2026-08-03 16:50:43,830 - directlfq.protein_intensity_estimation - INFO - lfq-object 5500
2026-08-03 16:50:44,148 - directlfq.protein_intensity_estimation - INFO - lfq-object 5900
2026-08-03 16:50:44,260 - directlfq.protein_intensity_estimation - INFO - lfq-object 5700
2026-08-03 16:50:44,396 - directlfq.protein_intensity_estimation - INFO - lfq-object 6100
2026-08-03 16:50:44,490 - directlfq.protein_intensity_estimation - INFO - lfq-object 5800
2026-08-03 16:50:44,562 - directlfq.protein_intensity_estimation - INFO - lfq-object 6000
2026-08-03 16:50:44,577 - directlfq.protein_intensity_estimation - INFO - lfq-object 6300
2026-08-03 16:50:44,858 - directlfq.protein_intensity_estimation - INFO - lfq-object 6200
2026-08-03 16:50:45,089 - directlfq.protein_intensity_estimation - INFO - lfq-object 6400
2026-08-03 16:50:45,103 - directlfq.protein_intensity_estimation - INFO - lfq-object 6600
2026-08-03 16:50:45,288 - directlfq.protein_intensity_estimation - INFO - lfq-object 6800
2026-08-03 16:50:45,423 - directlfq.protein_intensity_estimation - INFO - lfq-object 7000
2026-08-03 16:50:45,491 - directlfq.protein_intensity_estimation - INFO - lfq-object 6500
2026-08-03 16:50:45,494 - directlfq.protein_intensity_estimation - INFO - lfq-object 6700
2026-08-03 16:50:45,911 - directlfq.protein_intensity_estimation - INFO - lfq-object 6900
2026-08-03 16:50:46,660 - directlfq.protein_intensity_estimation - INFO - lfq-object 7100
2026-08-03 16:50:46,967 - directlfq.protein_intensity_estimation - INFO - lfq-object 7300
2026-08-03 16:50:47,039 - directlfq.protein_intensity_estimation - INFO - lfq-object 7400
2026-08-03 16:50:47,060 - directlfq.protein_intensity_estimation - INFO - lfq-object 7200
2026-08-03 16:50:47,076 - directlfq.protein_intensity_estimation - INFO - lfq-object 7500
2026-08-03 16:50:47,242 - directlfq.protein_intensity_estimation - INFO - lfq-object 7700
2026-08-03 16:50:47,546 - directlfq.protein_intensity_estimation - INFO - lfq-object 7600
2026-08-03 16:50:47,643 - directlfq.protein_intensity_estimation - INFO - lfq-object 7800
2026-08-03 16:50:47,652 - directlfq.protein_intensity_estimation - INFO - lfq-object 8000
2026-08-03 16:50:47,830 - directlfq.protein_intensity_estimation - INFO - lfq-object 8200
2026-08-03 16:50:47,839 - directlfq.protein_intensity_estimation - INFO - lfq-object 7900
2026-08-03 16:50:47,987 - directlfq.protein_intensity_estimation - INFO - lfq-object 8400
2026-08-03 16:50:48,009 - directlfq.protein_intensity_estimation - INFO - lfq-object 8300
2026-08-03 16:50:48,055 - directlfq.protein_intensity_estimation - INFO - lfq-object 8100
2026-08-03 16:50:48,476 - directlfq.protein_intensity_estimation - INFO - lfq-object 8500
2026-08-03 16:50:48,807 - directlfq.protein_intensity_estimation - INFO - lfq-object 8600
2026-08-03 16:50:48,825 - directlfq.protein_intensity_estimation - INFO - lfq-object 8700
2026-08-03 16:50:48,909 - directlfq.protein_intensity_estimation - INFO - lfq-object 8900
2026-08-03 16:50:49,008 - directlfq.protein_intensity_estimation - INFO - lfq-object 8800
2026-08-03 16:50:49,101 - directlfq.protein_intensity_estimation - INFO - lfq-object 9100
2026-08-03 16:50:49,477 - directlfq.protein_intensity_estimation - INFO - lfq-object 9200
2026-08-03 16:50:49,567 - directlfq.protein_intensity_estimation - INFO - lfq-object 9000
2026-08-03 16:50:49,737 - directlfq.protein_intensity_estimation - INFO - lfq-object 9600
2026-08-03 16:50:49,860 - directlfq.protein_intensity_estimation - INFO - lfq-object 9400
2026-08-03 16:50:49,872 - directlfq.protein_intensity_estimation - INFO - lfq-object 9700
2026-08-03 16:50:49,883 - directlfq.protein_intensity_estimation - INFO - lfq-object 9800
2026-08-03 16:50:50,138 - directlfq.protein_intensity_estimation - INFO - lfq-object 9900
2026-08-03 16:50:50,155 - directlfq.protein_intensity_estimation - INFO - lfq-object 9300
2026-08-03 16:50:50,187 - directlfq.protein_intensity_estimation - INFO - lfq-object 9500
2026-08-03 16:50:50,388 - directlfq.protein_intensity_estimation - INFO - lfq-object 10100
2026-08-03 16:50:50,476 - directlfq.protein_intensity_estimation - INFO - lfq-object 10000
2026-08-03 16:50:50,699 - directlfq.protein_intensity_estimation - INFO - lfq-object 10300
2026-08-03 16:50:50,753 - directlfq.protein_intensity_estimation - INFO - lfq-object 10200
2026-08-03 16:50:51,007 - directlfq.protein_intensity_estimation - INFO - lfq-object 10500
2026-08-03 16:50:51,245 - directlfq.protein_intensity_estimation - INFO - lfq-object 10400
2026-08-03 16:50:51,327 - directlfq.protein_intensity_estimation - INFO - lfq-object 10600
2026-08-03 16:50:51,628 - directlfq.protein_intensity_estimation - INFO - lfq-object 10800
2026-08-03 16:50:51,727 - directlfq.protein_intensity_estimation - INFO - lfq-object 10700
2026-08-03 16:50:51,811 - directlfq.protein_intensity_estimation - INFO - lfq-object 11000
2026-08-03 16:50:51,941 - directlfq.protein_intensity_estimation - INFO - lfq-object 11200
2026-08-03 16:50:52,077 - directlfq.protein_intensity_estimation - INFO - lfq-object 10900
2026-08-03 16:50:52,226 - directlfq.protein_intensity_estimation - INFO - lfq-object 11100
2026-08-03 16:50:52,311 - directlfq.protein_intensity_estimation - INFO - lfq-object 11300
2026-08-03 16:50:52,522 - directlfq.protein_intensity_estimation - INFO - lfq-object 11400
2026-08-03 16:50:53,458 - directlfq.protein_intensity_estimation - INFO - lfq-object 11500
2026-08-03 16:50:53,716 - directlfq.protein_intensity_estimation - INFO - lfq-object 11700
2026-08-03 16:50:53,854 - directlfq.protein_intensity_estimation - INFO - lfq-object 11900
2026-08-03 16:50:53,893 - directlfq.protein_intensity_estimation - INFO - lfq-object 11600
2026-08-03 16:50:54,147 - directlfq.protein_intensity_estimation - INFO - lfq-object 11800
2026-08-03 16:50:54,256 - directlfq.protein_intensity_estimation - INFO - lfq-object 12200
2026-08-03 16:50:54,427 - directlfq.protein_intensity_estimation - INFO - lfq-object 12000
2026-08-03 16:50:54,525 - directlfq.protein_intensity_estimation - INFO - lfq-object 12400
2026-08-03 16:50:54,659 - directlfq.protein_intensity_estimation - INFO - lfq-object 12600
2026-08-03 16:50:54,694 - directlfq.protein_intensity_estimation - INFO - lfq-object 12300
2026-08-03 16:50:54,713 - directlfq.protein_intensity_estimation - INFO - lfq-object 12100
2026-08-03 16:50:54,830 - directlfq.protein_intensity_estimation - INFO - lfq-object 12500
2026-08-03 16:50:55,123 - directlfq.protein_intensity_estimation - INFO - lfq-object 12700
2026-08-03 16:50:55,153 - directlfq.protein_intensity_estimation - INFO - lfq-object 12900
2026-08-03 16:50:55,394 - directlfq.protein_intensity_estimation - INFO - lfq-object 13100
2026-08-03 16:50:55,447 - directlfq.protein_intensity_estimation - INFO - lfq-object 13000
2026-08-03 16:50:55,457 - directlfq.protein_intensity_estimation - INFO - lfq-object 12800
2026-08-03 16:50:55,601 - directlfq.protein_intensity_estimation - INFO - lfq-object 13300
2026-08-03 16:50:55,803 - directlfq.protein_intensity_estimation - INFO - lfq-object 13200
2026-08-03 16:50:55,929 - directlfq.protein_intensity_estimation - INFO - lfq-object 13400
2026-08-03 16:50:56,250 - directlfq.protein_intensity_estimation - INFO - lfq-object 13600
2026-08-03 16:50:56,387 - directlfq.protein_intensity_estimation - INFO - lfq-object 13800
2026-08-03 16:50:56,468 - directlfq.protein_intensity_estimation - INFO - lfq-object 13500
2026-08-03 16:50:56,539 - directlfq.protein_intensity_estimation - INFO - lfq-object 14000
2026-08-03 16:50:56,674 - directlfq.protein_intensity_estimation - INFO - lfq-object 13700
2026-08-03 16:50:56,829 - directlfq.protein_intensity_estimation - INFO - lfq-object 13900
2026-08-03 16:50:56,832 - directlfq.protein_intensity_estimation - INFO - lfq-object 14100
2026-08-03 16:50:57,063 - directlfq.protein_intensity_estimation - INFO - lfq-object 14300
2026-08-03 16:50:57,207 - directlfq.protein_intensity_estimation - INFO - lfq-object 14500
2026-08-03 16:50:57,303 - directlfq.protein_intensity_estimation - INFO - lfq-object 14700
2026-08-03 16:50:57,341 - directlfq.protein_intensity_estimation - INFO - lfq-object 14200
2026-08-03 16:50:57,600 - directlfq.protein_intensity_estimation - INFO - lfq-object 14800
2026-08-03 16:50:57,634 - directlfq.protein_intensity_estimation - INFO - lfq-object 14400
2026-08-03 16:50:57,683 - directlfq.protein_intensity_estimation - INFO - lfq-object 14600
2026-08-03 16:50:57,981 - directlfq.protein_intensity_estimation - INFO - lfq-object 15000
2026-08-03 16:50:58,023 - directlfq.protein_intensity_estimation - INFO - lfq-object 14900
2026-08-03 16:50:58,150 - directlfq.protein_intensity_estimation - INFO - lfq-object 15200
2026-08-03 16:50:58,187 - directlfq.protein_intensity_estimation - INFO - lfq-object 15300
2026-08-03 16:50:58,300 - directlfq.protein_intensity_estimation - INFO - lfq-object 15400
2026-08-03 16:50:58,331 - directlfq.protein_intensity_estimation - INFO - lfq-object 15100
2026-08-03 16:50:58,452 - directlfq.protein_intensity_estimation - INFO - lfq-object 15500
2026-08-03 16:50:58,698 - directlfq.protein_intensity_estimation - INFO - lfq-object 15600
2026-08-03 16:50:58,808 - directlfq.protein_intensity_estimation - INFO - lfq-object 15700
2026-08-03 16:50:58,986 - directlfq.protein_intensity_estimation - INFO - lfq-object 15800
2026-08-03 16:50:59,307 - directlfq.protein_intensity_estimation - INFO - lfq-object 15900
2026-08-03 16:50:59,424 - directlfq.protein_intensity_estimation - INFO - lfq-object 16000
2026-08-03 16:50:59,466 - directlfq.protein_intensity_estimation - INFO - lfq-object 16100
2026-08-03 16:50:59,612 - directlfq.protein_intensity_estimation - INFO - lfq-object 16200
2026-08-03 16:50:59,776 - directlfq.protein_intensity_estimation - INFO - lfq-object 16300
2026-08-03 16:50:59,915 - directlfq.protein_intensity_estimation - INFO - lfq-object 16400
2026-08-03 16:51:01,149 - directlfq.protein_intensity_estimation - INFO - lfq-object 16500
2026-08-03 16:51:01,193 - directlfq.protein_intensity_estimation - INFO - lfq-object 16600
2026-08-03 16:51:01,309 - directlfq.protein_intensity_estimation - INFO - lfq-object 16700
2026-08-03 16:51:03,584 - directlfq.lfq_manager - INFO - Could not add additional columns to protein table, printing without additional columns.
2026-08-03 16:51:03,586 - directlfq.lfq_manager - INFO - Writing results files.
2026-08-03 16:51:06,035 - directlfq.lfq_manager - INFO - Analysis finished!
2026-08-03 16:51:06,051 - directlfq.lfq_manager - INFO - Starting directLFQ analysis.

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

2026-08-03 16:51:06,348 - directlfq.utils - INFO - using input type diann_precursors
2026-08-03 16:51:20,667 - directlfq.lfq_manager - INFO - Performing sample normalization.
2026-08-03 16:51:21,220 - directlfq.lfq_manager - INFO - Estimating lfq intensities.
2026-08-03 16:51:21,229 - directlfq.protein_intensity_estimation - INFO - 10432 lfq-groups total
2026-08-03 16:51:28,505 - directlfq.protein_intensity_estimation - INFO - using 60 processes
2026-08-03 16:51:28,601 - directlfq.protein_intensity_estimation - INFO - lfq-object 0
2026-08-03 16:51:29,023 - directlfq.protein_intensity_estimation - INFO - lfq-object 100
2026-08-03 16:51:29,178 - directlfq.protein_intensity_estimation - INFO - lfq-object 200
2026-08-03 16:51:29,229 - directlfq.protein_intensity_estimation - INFO - lfq-object 400
2026-08-03 16:51:29,492 - directlfq.protein_intensity_estimation - INFO - lfq-object 300
2026-08-03 16:51:29,507 - directlfq.protein_intensity_estimation - INFO - lfq-object 500
2026-08-03 16:51:29,592 - directlfq.protein_intensity_estimation - INFO - lfq-object 800
2026-08-03 16:51:29,784 - directlfq.protein_intensity_estimation - INFO - lfq-object 600
2026-08-03 16:51:29,944 - directlfq.protein_intensity_estimation - INFO - lfq-object 700
2026-08-03 16:51:30,263 - directlfq.protein_intensity_estimation - INFO - lfq-object 1100
2026-08-03 16:51:30,458 - directlfq.protein_intensity_estimation - INFO - lfq-object 900
2026-08-03 16:51:30,690 - directlfq.protein_intensity_estimation - INFO - lfq-object 1500
2026-08-03 16:51:30,720 - directlfq.protein_intensity_estimation - INFO - lfq-object 1200
2026-08-03 16:51:30,892 - directlfq.protein_intensity_estimation - INFO - lfq-object 1400
2026-08-03 16:51:30,902 - directlfq.protein_intensity_estimation - INFO - lfq-object 1000
2026-08-03 16:51:31,065 - directlfq.protein_intensity_estimation - INFO - lfq-object 1300
2026-08-03 16:51:31,151 - directlfq.protein_intensity_estimation - INFO - lfq-object 1600
2026-08-03 16:51:31,318 - directlfq.protein_intensity_estimation - INFO - lfq-object 1700
2026-08-03 16:51:31,498 - directlfq.protein_intensity_estimation - INFO - lfq-object 1900
2026-08-03 16:51:31,693 - directlfq.protein_intensity_estimation - INFO - lfq-object 1800
2026-08-03 16:51:31,736 - directlfq.protein_intensity_estimation - INFO - lfq-object 2200
2026-08-03 16:51:31,930 - directlfq.protein_intensity_estimation - INFO - lfq-object 2000
2026-08-03 16:51:32,158 - directlfq.protein_intensity_estimation - INFO - lfq-object 2100
2026-08-03 16:51:32,315 - directlfq.protein_intensity_estimation - INFO - lfq-object 2300
2026-08-03 16:51:32,397 - directlfq.protein_intensity_estimation - INFO - lfq-object 2400
2026-08-03 16:51:32,467 - directlfq.protein_intensity_estimation - INFO - lfq-object 2600
2026-08-03 16:51:32,473 - directlfq.protein_intensity_estimation - INFO - lfq-object 2500
2026-08-03 16:51:32,478 - directlfq.protein_intensity_estimation - INFO - lfq-object 2700
2026-08-03 16:51:32,797 - directlfq.protein_intensity_estimation - INFO - lfq-object 2800
2026-08-03 16:51:32,855 - directlfq.protein_intensity_estimation - INFO - lfq-object 3000
2026-08-03 16:51:32,877 - directlfq.protein_intensity_estimation - INFO - lfq-object 2900
2026-08-03 16:51:33,081 - directlfq.protein_intensity_estimation - INFO - lfq-object 3300
2026-08-03 16:51:33,270 - directlfq.protein_intensity_estimation - INFO - lfq-object 3400
2026-08-03 16:51:33,339 - directlfq.protein_intensity_estimation - INFO - lfq-object 3200
2026-08-03 16:51:33,459 - directlfq.protein_intensity_estimation - INFO - lfq-object 3500
2026-08-03 16:51:33,483 - directlfq.protein_intensity_estimation - INFO - lfq-object 3700
2026-08-03 16:51:33,546 - directlfq.protein_intensity_estimation - INFO - lfq-object 3600
2026-08-03 16:51:33,689 - directlfq.protein_intensity_estimation - INFO - lfq-object 3800
2026-08-03 16:51:33,958 - directlfq.protein_intensity_estimation - INFO - lfq-object 3900
2026-08-03 16:51:34,158 - directlfq.protein_intensity_estimation - INFO - lfq-object 4100
2026-08-03 16:51:34,283 - directlfq.protein_intensity_estimation - INFO - lfq-object 3100
2026-08-03 16:51:34,384 - directlfq.protein_intensity_estimation - INFO - lfq-object 4200
2026-08-03 16:51:34,492 - directlfq.protein_intensity_estimation - INFO - lfq-object 4400
2026-08-03 16:51:34,883 - directlfq.protein_intensity_estimation - INFO - lfq-object 4500
2026-08-03 16:51:35,035 - directlfq.protein_intensity_estimation - INFO - lfq-object 4700
2026-08-03 16:51:35,097 - directlfq.protein_intensity_estimation - INFO - lfq-object 4600
2026-08-03 16:51:35,173 - directlfq.protein_intensity_estimation - INFO - lfq-object 4000
2026-08-03 16:51:35,207 - directlfq.protein_intensity_estimation - INFO - lfq-object 4300
2026-08-03 16:51:36,178 - directlfq.protein_intensity_estimation - INFO - lfq-object 4800
2026-08-03 16:51:36,616 - directlfq.protein_intensity_estimation - INFO - lfq-object 4900
2026-08-03 16:51:36,846 - directlfq.protein_intensity_estimation - INFO - lfq-object 5000
2026-08-03 16:51:37,097 - directlfq.protein_intensity_estimation - INFO - lfq-object 5200
2026-08-03 16:51:37,152 - directlfq.protein_intensity_estimation - INFO - lfq-object 5100
2026-08-03 16:51:37,297 - directlfq.protein_intensity_estimation - INFO - lfq-object 5500
2026-08-03 16:51:37,494 - directlfq.protein_intensity_estimation - INFO - lfq-object 5300
2026-08-03 16:51:37,502 - directlfq.protein_intensity_estimation - INFO - lfq-object 5600
2026-08-03 16:51:37,723 - directlfq.protein_intensity_estimation - INFO - lfq-object 5400
2026-08-03 16:51:37,817 - directlfq.protein_intensity_estimation - INFO - lfq-object 5800
2026-08-03 16:51:37,835 - directlfq.protein_intensity_estimation - INFO - lfq-object 5900
2026-08-03 16:51:38,127 - directlfq.protein_intensity_estimation - INFO - lfq-object 6000
2026-08-03 16:51:38,226 - directlfq.protein_intensity_estimation - INFO - lfq-object 5700
2026-08-03 16:51:38,418 - directlfq.protein_intensity_estimation - INFO - lfq-object 6100
2026-08-03 16:51:38,596 - directlfq.protein_intensity_estimation - INFO - lfq-object 6200
2026-08-03 16:51:39,047 - directlfq.protein_intensity_estimation - INFO - lfq-object 6300
2026-08-03 16:51:39,258 - directlfq.protein_intensity_estimation - INFO - lfq-object 6400
2026-08-03 16:51:39,400 - directlfq.protein_intensity_estimation - INFO - lfq-object 6700
2026-08-03 16:51:39,536 - directlfq.protein_intensity_estimation - INFO - lfq-object 6500
2026-08-03 16:51:39,627 - directlfq.protein_intensity_estimation - INFO - lfq-object 7000
2026-08-03 16:51:39,634 - directlfq.protein_intensity_estimation - INFO - lfq-object 6800
2026-08-03 16:51:39,797 - directlfq.protein_intensity_estimation - INFO - lfq-object 6900
2026-08-03 16:51:39,910 - directlfq.protein_intensity_estimation - INFO - lfq-object 7100
2026-08-03 16:51:40,034 - directlfq.protein_intensity_estimation - INFO - lfq-object 7200
2026-08-03 16:51:40,224 - directlfq.protein_intensity_estimation - INFO - lfq-object 6600
2026-08-03 16:51:40,360 - directlfq.protein_intensity_estimation - INFO - lfq-object 7400
2026-08-03 16:51:40,452 - directlfq.protein_intensity_estimation - INFO - lfq-object 7300
2026-08-03 16:51:40,526 - directlfq.protein_intensity_estimation - INFO - lfq-object 7500
2026-08-03 16:51:40,697 - directlfq.protein_intensity_estimation - INFO - lfq-object 7700
2026-08-03 16:51:40,799 - directlfq.protein_intensity_estimation - INFO - lfq-object 7600
2026-08-03 16:51:40,855 - directlfq.protein_intensity_estimation - INFO - lfq-object 7800
2026-08-03 16:51:41,081 - directlfq.protein_intensity_estimation - INFO - lfq-object 7900
2026-08-03 16:51:41,312 - directlfq.protein_intensity_estimation - INFO - lfq-object 8100
2026-08-03 16:51:41,393 - directlfq.protein_intensity_estimation - INFO - lfq-object 8000
2026-08-03 16:51:41,639 - directlfq.protein_intensity_estimation - INFO - lfq-object 8200
2026-08-03 16:51:41,812 - directlfq.protein_intensity_estimation - INFO - lfq-object 8300
2026-08-03 16:51:41,961 - directlfq.protein_intensity_estimation - INFO - lfq-object 8500
2026-08-03 16:51:42,097 - directlfq.protein_intensity_estimation - INFO - lfq-object 8400
2026-08-03 16:51:42,155 - directlfq.protein_intensity_estimation - INFO - lfq-object 8600
2026-08-03 16:51:42,282 - directlfq.protein_intensity_estimation - INFO - lfq-object 8800
2026-08-03 16:51:42,524 - directlfq.protein_intensity_estimation - INFO - lfq-object 8900
2026-08-03 16:51:42,527 - directlfq.protein_intensity_estimation - INFO - lfq-object 8700
2026-08-03 16:51:43,983 - directlfq.protein_intensity_estimation - INFO - lfq-object 9000
2026-08-03 16:51:44,086 - directlfq.protein_intensity_estimation - INFO - lfq-object 9200
2026-08-03 16:51:44,273 - directlfq.protein_intensity_estimation - INFO - lfq-object 9100
2026-08-03 16:51:44,294 - directlfq.protein_intensity_estimation - INFO - lfq-object 9300
2026-08-03 16:51:44,543 - directlfq.protein_intensity_estimation - INFO - lfq-object 9400
2026-08-03 16:51:44,551 - directlfq.protein_intensity_estimation - INFO - lfq-object 9600
2026-08-03 16:51:44,835 - directlfq.protein_intensity_estimation - INFO - lfq-object 9700
2026-08-03 16:51:44,875 - directlfq.protein_intensity_estimation - INFO - lfq-object 9900
2026-08-03 16:51:44,825 - directlfq.protein_intensity_estimation - INFO - lfq-object 9500
2026-08-03 16:51:44,882 - directlfq.protein_intensity_estimation - INFO - lfq-object 9800
2026-08-03 16:51:45,108 - directlfq.protein_intensity_estimation - INFO - lfq-object 10000
2026-08-03 16:51:45,375 - directlfq.protein_intensity_estimation - INFO - lfq-object 10100
2026-08-03 16:51:45,515 - directlfq.protein_intensity_estimation - INFO - lfq-object 10300
2026-08-03 16:51:45,779 - directlfq.protein_intensity_estimation - INFO - lfq-object 10200
2026-08-03 16:51:45,890 - directlfq.protein_intensity_estimation - INFO - lfq-object 10400
2026-08-03 16:51:56,148 - directlfq.lfq_manager - INFO - Writing results files.
2026-08-03 16:51:58,578 - directlfq.lfq_manager - INFO - Analysis finished!

fragpipe24_LFQbench_msfragger

fragpipe24_LFQbenchTOF_diatracer_triqler

tmp

fragpipe24_LFQbench_umpire

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

fragpipe24_LFQbench.sh

diann231_LFQbench

fragpipe24_ups_ecoli_umpire_triqler

fragpipe24_ups_ecoli_msfragger

diann231_ups_ecoli

fragpipe24_UPS-Ecoli.sh

## directLFQ p-value estimation LFQbench timsTOF

In [66]:
imputation = 'min'
quant = 'directlfq'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            inpath = path.join('./search_results', search_dr, 'dia-quant-output', 'report.tsv.protein_intensities.tsv')
            prot_col=''
        else :
            inpath = path.join('./search_results', search_dr, 'report.parquet.protein_intensities.tsv')
            prot_col='protein'
        if path.exists(inpath) :
            colstarter = 'LFQ_timsTOFPro_diaPASEF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(path.dirname(inpath), 'quant_{}_{}.tsv'.format(quant, imputation))
            print(save_path)
            try :
                se = search_dr.split('LFQbenchTOF')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            print(inpath)
            de, h_de, e_de, y_de, lfq_df = manual_quant(inpath, 
                                                        colstarter=colstarter, 
                                                        colsplitter=colsplitter, 
                                                        condstarter='Condition_',
                                                        organism_dict=lfqbench_organism_dict, 
                                                        prot_col=prot_col,
                                                        imputation=imputation, 
                                                        max_nan=9,
                                                        min_fc=0.5, 
                                                        search_engine=se, 
                                                        quant=quant,
                                                        save_path=save_path)
            print('manual', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

diann231_LFQbenchTOF

./search_results/diann231_LFQbenchTOF/quant_directlfq_min.tsv
./search_results/diann231_LFQbenchTOF/report.parquet.protein_intensities.tsv
['protein', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_01', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_03', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_01', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_02', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_03', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_01', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_02', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_03', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_01', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_02', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_03', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_01', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_02', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_03', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_01', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_02', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_03']
manual diann231_LFQbenchTOF done

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

./search_results/fragpipe24_LFQbenchTOF_diatracer/dia-quant-output/quant_directlfq_min.tsv
./search_results/fragpipe24_LFQbenchTOF_diatracer/dia-quant-output/report.tsv.protein_intensities.tsv
['protein', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_01', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_03', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_01', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_02', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_03', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_01', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_02', 'LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_03', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_01', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_02', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_03', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_01', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_02', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_03', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_01', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_02', 'LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_03', 'Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes']
manual fragpipe24_LFQbenchTOF_diatracer done

fragpipe24_LFQbench_msfragger

fragpipe24_LFQbenchTOF_diatracer_triqler

tmp

fragpipe24_LFQbench_umpire

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

fragpipe24_LFQbench.sh

diann231_LFQbench

fragpipe24_ups_ecoli_umpire_triqler

fragpipe24_ups_ecoli_msfragger

diann231_ups_ecoli

fragpipe24_UPS-Ecoli.sh

## Manual LFQbench timsTOF

In [68]:
imputation = 'min'
for search_dr in listdir('./search_results') :
    print(search_dr, '\n')
    if 'LFQbench' in search_dr and 'TOF' in search_dr and path.isdir(path.join('./search_results', search_dr)) and not 'triqler' in search_dr :
        if search_dr.startswith('fragpipe') :
            workdir = path.join('./search_results', search_dr, 'dia-quant-output')
        else :
            workdir = path.join('./search_results', search_dr)
        # try :
        inpath = path.join(workdir, 'report.pg_matrix.tsv')
        if path.exists(inpath) :
            colstarter = './input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_' # 10fmol_inj2.mzML'
            colsplitter = 'Sample'
            save_path = path.join(workdir, 'quant_manual_{}.tsv'.format(imputation))
            try :
                se = search_dr.split('LFQbench')[-1].split('_')[1]
            except :
                se = search_dr.split('_')[0]
            de, h_de, e_de, y_de, lfq_df = manual_quant(inpath, 
                                                        colstarter=colstarter, 
                                                        colsplitter=colsplitter, 
                                                        condstarter='Condition_',
                                                        organism_dict=lfqbench_organism_dict, 
                                                        imputation=imputation, 
                                                        max_nan=9,
                                                        min_fc=0.5, 
                                                        search_engine=se, 
                                                        quant='manual',
                                                        save_path=save_path)
            print('manual', search_dr, 'done\n')
        else :
            print('no input file in', search_dr)

diann231_LFQbenchTOF

['Protein.Group', 'Protein.Names', 'Genes', 'First.Protein.Description', 'N.Sequences', 'N.Proteotypic.Sequences', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_03.d']
manual diann231_LFQbenchTOF done

fragpipe24_LFQbench_msfragger_triqler

fragpipe24_ups_ecoli_umpire

fragpipe24_LFQbenchTOF_diatracer

['Protein.Group', 'Protein.Ids', 'Protein.Names', 'Genes', 'First.Protein.Description', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Beta_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Gamma_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Alpha_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_A_Sample_Alpha_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_03.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_02.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Beta_01.d', '/home/lerost/DIA_tools_manuscript/input_files/LFQbench_timsTOF/LFQ_timsTOFPro_diaPASEF_Condition_B_Sample_Gamma_02.d']
manual fragpipe24_LFQbenchTOF_diatracer done

fragpipe24_LFQbench_msfragger

fragpipe24_LFQbenchTOF_diatracer_triqler

tmp

fragpipe24_LFQbench_umpire

.ipynb_checkpoints

fragpipe24_ups_ecoli_msfragger_triqler

diann231_ups_ecoli_triqler

fragpipe24_LFQbench_umpire_triqler

fragpipe24_LFQbench.sh

diann231_LFQbench

fragpipe24_ups_ecoli_umpire_triqler

fragpipe24_ups_ecoli_msfragger

diann231_ups_ecoli

fragpipe24_UPS-Ecoli.sh

## Copy output quant tables into quantitation directory

In [15]:
for dr in listdir('./search_results') :
    quants = 0
    if path.isdir(path.join('./search_results', dr)) : 
        if any([el.startswith('quant_') for el in listdir(path.join('./search_results', dr))]) :
            quants = sum([el.startswith('quant_') for el in listdir(path.join('./search_results', dr))])
            for el in listdir(path.join('./search_results', dr)) :
                if el.startswith('quant_') :
                    old_path = path.join('./search_results', dr, el)
                    new_path = path.join('./quantitation', dr + '_' + el)
                    !cp $old_path $new_path
            print( path.join('./search_results', dr), quants, sep='\t' )
        # else :
        #     print(1, path.join('./search_results', dr))
        elif path.isdir(path.join('./search_results', dr, 'dia-quant-output')) :
            if any([el.startswith('quant_') for el in listdir(path.join('./search_results', dr, 'dia-quant-output'))]) :
                quants = sum([el.startswith('quant_') for el in listdir(path.join('./search_results', dr, 'dia-quant-output'))])
                for el in listdir(path.join('./search_results', dr, 'dia-quant-output')) :
                    if el.startswith('quant_') :
                        old_path = path.join('./search_results', dr, 'dia-quant-output', el)
                        new_path = path.join('./quantitation', dr + '_' + el)
                        !cp $old_path $new_path
                print( path.join('./search_results', dr), quants, sep='\t' )
        elif 'ups_ecoli' in path.join('./search_results', dr) :
            for comp in listdir(path.join('./search_results', dr)) :
                quants = 0
                if path.isdir(path.join('./search_results', dr, comp, 'dia-quant-output')) :
                    if any([el.startswith('quant_') for el in listdir(path.join('./search_results', dr, comp, 'dia-quant-output'))]) :
                        quants = sum([el.startswith('quant_') for el in listdir(path.join('./search_results', dr, comp, 'dia-quant-output'))])
                        for el in listdir(path.join('./search_results', dr, comp, 'dia-quant-output')) :
                            if el.startswith('quant_') :
                                old_path = path.join('./search_results', dr, comp, 'dia-quant-output', el)
                                new_path = path.join('./quantitation', dr, comp + '_' + el)
                                !cp $old_path $new_path
                        print( path.join('./search_results', dr, comp), quants, sep='\t')
                    else :
                        print(2, path.join('./search_results', dr, comp))
                elif path.isdir(path.join('./search_results', dr, comp)) :
                    if any([el.startswith('quant_') for el in listdir(path.join('./search_results', dr, comp))]) :
                        quants = sum([el.startswith('quant_') for el in listdir(path.join('./search_results', dr, comp))])
                        for el in listdir(path.join('./search_results', dr, comp)) :
                            if el.startswith('quant_') :
                                old_path = path.join('./search_results', dr, comp, el)
                                new_path = path.join('./quantitation', dr, comp + '_' + el)
                                !cp $old_path $new_path
                        print( path.join('./search_results', dr, comp), quants, sep='\t')
                    else :
                        print(2, path.join('./search_results', dr, comp))
        else :
            print('error', path.join('./search_results', dr) )

./search_results/diann231_LFQbenchTOF	4
./search_results/fragpipe24_ups_ecoli_umpire/5fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/25fmol_vs_2_5fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/2_5fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/25fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/50fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/25fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/25fmol_vs_10fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/50fmol_vs_10fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/10fmol_vs_2_5fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/50fmol_vs_25fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/10fmol_vs_5fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/50fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/5fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/1fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/5fmol_vs_2_5fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/10fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/50fmol_vs_2_5fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/10fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/2_5fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/10fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/25fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/50fmol_vs_5fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/1fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/2_5fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/50fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/5fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/0_25fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_umpire/25fmol_vs_5fmol	4
./search_results/fragpipe24_LFQbenchTOF_diatracer	4
./search_results/fragpipe24_LFQbench_msfragger	5
2 ./search_results/diann181_ups_ecoli_pg_intensities/.ipynb_checkpoints
error ./search_results/tmp
./search_results/fragpipe24_LFQbench_umpire	5
error ./search_results/.ipynb_checkpoints
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/5fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/5fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/50fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/10fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/50fmol_vs_5fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/10fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/25fmol_vs_2_5fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/5fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/2_5fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/50fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/10fmol_vs_2_5fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/25fmol_vs_5fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/25fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/0_25fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/2_5fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/5fmol_vs_2_5fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/1fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/10fmol_vs_5fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/50fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/2_5fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/50fmol_vs_2_5fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/10fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/50fmol_vs_25fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/25fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/25fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/50fmol_vs_10fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/1fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_msfragger_triqler/25fmol_vs_10fmol
2 ./search_results/diann231_ups_ecoli_triqler/50fmol_vs_25fmol
2 ./search_results/diann231_ups_ecoli_triqler/10fmol_vs_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/50fmol_vs_5fmol
2 ./search_results/diann231_ups_ecoli_triqler/50fmol_vs_10fmol
2 ./search_results/diann231_ups_ecoli_triqler/25fmol_vs_10fmol
2 ./search_results/diann231_ups_ecoli_triqler/10fmol_vs_0_25fmol
2 ./search_results/diann231_ups_ecoli_triqler/50fmol_vs_2_5fmol
2 ./search_results/diann231_ups_ecoli_triqler/25fmol_vs_5fmol
2 ./search_results/diann231_ups_ecoli_triqler/5fmol_vs_2_5fmol
2 ./search_results/diann231_ups_ecoli_triqler/1fmol_vs_0_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/10fmol_vs_0_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/50fmol_vs_0_25fmol
2 ./search_results/diann231_ups_ecoli_triqler/25fmol_vs_0_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/1fmol_vs_0_25fmol
2 ./search_results/diann231_ups_ecoli_triqler/25fmol_vs_0_25fmol
2 ./search_results/diann231_ups_ecoli_triqler/25fmol_vs_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/2_5fmol_vs_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/2_5fmol_vs_0_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/5fmol_vs_0_25fmol
2 ./search_results/diann231_ups_ecoli_triqler/25fmol_vs_2_5fmol
2 ./search_results/diann231_ups_ecoli_triqler/5fmol_vs_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/0_25fmol_vs_0_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/50fmol_vs_0_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/5fmol_vs_0_1fmol
2 ./search_results/diann231_ups_ecoli_triqler/2_5fmol_vs_0_25fmol
2 ./search_results/diann231_ups_ecoli_triqler/10fmol_vs_2_5fmol
2 ./search_results/diann231_ups_ecoli_triqler/10fmol_vs_5fmol
2 ./search_results/diann231_ups_ecoli_triqler/50fmol_vs_1fmol
error ./search_results/diann231_25fmol_vs_5fmol_rerun
./search_results/diann231_LFQbench	5
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/5fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/25fmol_vs_2_5fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/5fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/5fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/50fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/10fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/10fmol_vs_2_5fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/50fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/50fmol_vs_5fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/2_5fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/2_5fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/25fmol_vs_5fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/10fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/0_25fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/25fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/50fmol_vs_2_5fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/10fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/5fmol_vs_2_5fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/1fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/25fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/1fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/25fmol_vs_0_25fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/10fmol_vs_5fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/50fmol_vs_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/50fmol_vs_25fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/2_5fmol_vs_0_1fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/50fmol_vs_10fmol
2 ./search_results/fragpipe24_ups_ecoli_umpire_triqler/25fmol_vs_10fmol
./search_results/fragpipe24_ups_ecoli_msfragger/2_5fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/0_25fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/25fmol_vs_5fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/2_5fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/25fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/25fmol_vs_2_5fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/5fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/5fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/5fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/50fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/2_5fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/10fmol_vs_2_5fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/10fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/50fmol_vs_5fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/10fmol_vs_5fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/50fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/50fmol_vs_10fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/25fmol_vs_10fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/50fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/50fmol_vs_25fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/50fmol_vs_2_5fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/25fmol_vs_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/10fmol_vs_0_1fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/10fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/25fmol_vs_0_1fmol	4
2 ./search_results/fragpipe24_ups_ecoli_msfragger/.ipynb_checkpoints
./search_results/fragpipe24_ups_ecoli_msfragger/5fmol_vs_2_5fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/1fmol_vs_0_25fmol	4
./search_results/fragpipe24_ups_ecoli_msfragger/1fmol_vs_0_1fmol	4
./search_results/diann231_ups_ecoli/50fmol_vs_0_25fmol	4
./search_results/diann231_ups_ecoli/25fmol_vs_1fmol	4
./search_results/diann231_ups_ecoli/5fmol_vs_0_1fmol	4
./search_results/diann231_ups_ecoli/50fmol_vs_2_5fmol	4
./search_results/diann231_ups_ecoli/10fmol_vs_5fmol	4
./search_results/diann231_ups_ecoli/50fmol_vs_1fmol	4
./search_results/diann231_ups_ecoli/2_5fmol_vs_1fmol	4
./search_results/diann231_ups_ecoli/10fmol_vs_0_1fmol	4
./search_results/diann231_ups_ecoli/10fmol_vs_0_25fmol	4
./search_results/diann231_ups_ecoli/5fmol_vs_1fmol	4
./search_results/diann231_ups_ecoli/25fmol_vs_0_1fmol	4
./search_results/diann231_ups_ecoli/1fmol_vs_0_25fmol	4
./search_results/diann231_ups_ecoli/0_25fmol_vs_0_1fmol	4
./search_results/diann231_ups_ecoli/10fmol_vs_1fmol	4
./search_results/diann231_ups_ecoli/50fmol_vs_5fmol	4
./search_results/diann231_ups_ecoli/5fmol_vs_2_5fmol	4
./search_results/diann231_ups_ecoli/1fmol_vs_0_1fmol	4
./search_results/diann231_ups_ecoli/2_5fmol_vs_0_25fmol	4
./search_results/diann231_ups_ecoli/25fmol_vs_2_5fmol	4
./search_results/diann231_ups_ecoli/5fmol_vs_0_25fmol	4
./search_results/diann231_ups_ecoli/2_5fmol_vs_0_1fmol	4
./search_results/diann231_ups_ecoli/50fmol_vs_0_1fmol	4
./search_results/diann231_ups_ecoli/50fmol_vs_10fmol	4
./search_results/diann231_ups_ecoli/25fmol_vs_10fmol	4
./search_results/diann231_ups_ecoli/25fmol_vs_5fmol	4
./search_results/diann231_ups_ecoli/25fmol_vs_0_25fmol	4
./search_results/diann231_ups_ecoli/10fmol_vs_2_5fmol	4
./search_results/diann231_ups_ecoli/50fmol_vs_25fmol	4